### PR TITLE
fix persistence

### PR DESCRIPTION
**Pull request by ab9rf**
the save folder moved

### CODE REVIEW

**Review by myk002 — APPROVED** [review]

**Comment by myk002** [comment]
it's interesting that the docs builds take longer than the binary build. ccache is really helping, it seems.

**Comment by lethosor** [comment]
Lack of plugins also helps :)

Did either of you happen to check for other occurrences of "data/save"?

**Comment by myk002** [comment]
yeah, there's quite a bit more there. I'll file a bug to go through and migrate it

**Comment by ab9rf** [comment]
> Lack of plugins also helps :)
> 
> Did either of you happen to check for other occurrences of "data/save"?

there's definitely one in `autogems` i happened to find yesterday, i'm sure there are others

**Pull request merged**
