### PR TITLE
[quickfort] new alias structure

### PR DESCRIPTION
**Pull request by TSM-EVO**
Files created with `savestock` for each existing [alias](https://docs.dfhack.org/en/stable/docs/guides/quickfort-alias-guide.html). Some aliases missing (search as an example) currently.

### CODE REVIEW

**Comment by TSM-EVO** [comment]
Refuse piles are also not currently represented correctly, due to #2977

**Comment by myk002** [comment]
let me see if I can get the refuse exporting fixed before we merge this PR

**Comment by myk002** [comment]
I actually can't reproduce the specific error here. could I get a copy of the world you're using?

**Comment by myk002** [comment]
Refuse pile errors should be fixed now that #3005 is merged. Could you try those again?

**Comment by myk002** [comment]
mentioning #2974 to link this PR to that issue

**Comment by TSM-EVO** [comment]
The refuse files are now nonzero and working,

**Review by myk002 — APPROVED** [review]
Thanks you for creating these!

**Pull request merged**
