### PR TITLE
auto_ptr is deprecated

### PR DESCRIPTION
**Pull request by BenLubar**
use unique_ptr instead, ~~with the C++14 helper function make_unique.~~

### CODE REVIEW

**Comment by BenLubar** [comment]
Ugh, we're using C++14 on Windows but C++11 on Linux?

**Comment by lethosor** [comment]
make_unique would be nice. Does GCC 4.8 not support that?

**Comment by BenLubar** [comment]
It apparently requires GCC 4.9 or higher.

**Comment by lethosor** [comment]
We could write our own pretty easily. I'm not sure forcing a GCC upgrade on people would be suitable just for that.

(This solution also works, of course.)

**Pull request merged**
