### PR TITLE
update new authors from 01 Feb 2023 - 15 Apr 2023

### LINKED ISSUE #3237: Ensure the authors list is up to date
It's been a while and we should check to make sure we haven't missed anyone recently

### PR DESCRIPTION
**Pull request by myk002**
from scanning the git commit logs in dfhack, scripts. and structures

Fixes #3237

### CODE REVIEW

**Comment by myk002** [comment]
Authors, could you check how I added your names and suggest corrections?

**Comment by silverflyone** [comment]
> @silverflyone @TSM-EVO @PopnROFL
> 
> Authors, could you correct my additions with how you'd like yourselves represented?

Silver is fine with, if no one else uses it. Thanks Myk.

**Comment by TSM-EVO** [comment]
Will H would be good for me.

**Comment by Cubittus** [comment]
If ok, I'll have my meatspace name, Alex Blamey, in the name column.

**Comment by myk002** [comment]
Names updated. Thanks!

**Comment by myk002** [comment]
Merging. If anyone wants to change how they're listed here, please message me (or submit a PR)

**Pull request merged**
