### PR TITLE
Update stockpiles.lua to add functionality to import/export that was a work in progress before modification. 

### PR DESCRIPTION
**Pull request by unboundlopez**
Added functionality to import export on the stockpile menu.

Fixes: https://github.com/DFHack/dfhack/issues/4999

### CODE REVIEW

**Comment by unboundlopez** [comment]
pre-commit.ci autofix

**Comment by unboundlopez** [comment]
https://github.com/user-attachments/assets/0cb6f04d-5ad9-4235-b45e-e8e6a9a20960

**Comment by chdoc** [comment]
@myk002 Could you provide some context on https://github.com/DFHack/dfhack/commit/856237cfd3e92124b7cf3dab3e76ede850457d4c (Part of https://github.com/DFHack/dfhack/pull/3285)

It looks to me like the functionality provided by this PR was already partially implemented, but commented out, beforehand.

**Comment by ab9rf** [comment]
Please give this PR a more descriptive name than "update stockpiles.lua"

**Comment by unboundlopez** [comment]
Updated the title.

**Comment by myk002** [comment]
> @myk002 Could you provide some context on [856237c](https://github.com/DFHack/dfhack/commit/856237cfd3e92124b7cf3dab3e76ede850457d4c) (Part of #3285)
> 
> It looks to me like the functionality provided by this PR was already partially implemented, but commented out, beforehand.

Yeah, I got scared off from designing a UI that would make generated material filters and property filters intuitive. The `stockpiles` API is quite intimidating (and I say that even though I'm the one who wrote it).

However, a simple approach like what this PR implements would at least be useful for copy/pasting stockpiles within a single fort, which is still a worthy use case.

**Pull request merged**
