### PR TITLE
linux: preserve existing LD_PRELOAD content

### PR DESCRIPTION
**Pull request by Jajcus**
that is needed for Steam overlay and game streaming to work

fixes https://github.com/DFHack/dfhack/issues/3768

### CODE REVIEW

**Review by myk002 — COMMENTED** [review]
Thanks for this! Could you add a line to `docs/changelog.txt` under the "Fixes" header for the "Future" version?

Also, please feel free to add your name to the `docs/about/Authors.rst` file

**Review by lethosor — CHANGES_REQUESTED** [review]
We already have PRELOAD_LIB for this purpose. Is that not usable in your case? 

The reason for the separate variable is because if LD_PRELOAD is set, *every process in the launcher script* will preload the specified libraries. That includes every `echo` command, `gdb`, `strace`, `stty`, etc. In the case of GDB and others, that can cause unexpected behavior.

If we need to pull in LD_PRELOAD because of limitations on the Steam side, we should also clear LD_PRELOAD after adding its contents to PRELOAD_LIB.

**Comment by Jajcus** [comment]
> Thanks for this! Could you add a line to docs/changelog.txt under the "Fixes" header for the "Future" version?>>
>
> Also, please feel free to add your name to the docs/about/Authors.rst file

Will do that tomorrow, with other changes.

> We already have PRELOAD_LIB for this purpose. Is that not usable in your case?

I do put LD_PRELOAD into PRELOAD_LIB, as that is used to set LD_PRELOAD (the actual mechanism to preload libraries in Linux).
Now I think this is not the optimal solution, though I do not fully understand what is the meaning of PRELOAD_LIB, so I just did the simplest thing.

I will try to find something a bit better.

> The reason for the separate variable is because if LD_PRELOAD is set, every process in the launcher script will preload the specified libraries.

This should not be a problem – that is what steam expects with its use of LD_PRELOAD and preloading libs in Linux is AFAIK very cheap (these are called 'shared libraries' for a reason).

> In the case of GDB and others, that can cause unexpected behavior.

Running GDB without the LDD environment the application requires can also give unexpected results.

**Comment by Jajcus** [comment]
I have updated the commit not to modify ``$PRELOAD_LIB``, just make sure  current ``$LD_PRELOAD`` contents is preserved everywhere where ``$LD_PRELOAD`` is set.

This would probably only matter in case the script is run recursively or if anything else uses ``$PRELOAD_LIB`` set there, which does not seem to be the case. Seems reasonable thing to do anyway.

**Comment by lethosor** [comment]
> Now I see how it is currently handled – my current change would also be cover that – LD_PRELOAD is only set when it was already being set to $PRELOAD_LIB.

Ok, this is fine. What I had in mind was actually unsetting `LD_PRELOAD` after adding its contents to `PRELOAD_LIB`, just to avoid modifying 10 places in the same way, but your way works too, and we already have some duplication between branches.

> This should not be a problem – that is what steam expects with its use of LD_PRELOAD and preloading libs in Linux is AFAIK very cheap (these are called 'shared libraries' for a reason).

The problem I am pointing out is that we _shouldn't_ be preloading DFHack with LD_PRELOAD for processes other than DF. It's not a problem of not being "cheap" - it's a problem with introducing unexpected behavior. I don't have specific examples, but I know we have had trouble with preloading libdfhack into a process that isn't DF.

**Review by lethosor — APPROVED** [review]

**Comment by Jajcus** [comment]
>  It's not a problem of not being "cheap" - it's a problem with introducing unexpected behavior.

Fair enough.

Anyway – may change does not change where the dfhack libraries preload is enabled.

**Pull request merged**
