### PR TITLE
Embark assistant

### PR DESCRIPTION
**Pull request by PatrikLundell**
Added scrolling of Finder search criteria, plus the new criterion of Frozen.

As expected, the changelog.txt update has to be handled manually.

### CODE REVIEW

**Comment by lethosor** [comment]
@BenLubar not sure why buildmaster broke - maybe because of the merge conflict?

Anyway, I'm not sure why CodeFactor is complaining, since you didn't touch those lines.

**Comment by BenLubar** [comment]
@lethosor yeah, It tries to fetch `refs/pull/1362/merge` but that doesn't exist if there's a conflict.

**Comment by lethosor** [comment]
Interestingly, Travis just didn't run on that commit. Maybe it's something you could check for as well?

**Comment by BenLubar** [comment]
Looks like it ran - it just took a few seconds to start up.

**Comment by lethosor** [comment]
I'm talking about https://github.com/DFHack/dfhack/pull/1362/commits/fdf52deb367df82b88ed4ed36d4f06c6a1a79454, which is the last commit before my merge and just has 3 statuses reported.

**Comment by PatrikLundell** [comment]
Damned be Travis! The idiot thing finds using constants rather than spamming literals to be "complex code", and it does the same thing with using local variables.

**Comment by lethosor** [comment]
That's CodeFactor, not Travis. It's a new thing we don't pay much attention to because it flags a lot of DFHack code too. Just ignore it for now - your PR didn't make anything much worse.

**Comment by PatrikLundell** [comment]
I did get rid of the blank lines. Your merging 'develop' into this branch caused some trouble on my end, as I suddenly couldn't update my update because there were remote changes... VC didn't like it after it had been pulled down, but 'git submodule init' (doing nothing), followed by 'git submodule update' (which did something json-whaterer) caused install-debug to run successfully, but VC still fails on 6 things, one of which is protobuf.

**Comment by lethosor** [comment]
What specifically happened when you ran "git pull"? There weren't any submodule changes here (except maybe scripts, which don't affect your PR), so the submodule commands wouldn't have done anything.

**Comment by PatrikLundell** [comment]
Looking back at the history, it was just scripts that was updated, so I guess some of the files of the pull did something VC didn't like (or detect). CMakeLists.txt, CMakeSettings.json, plugins/ruby/codegen.pl, plugins/ruby/ruby-autogen-defs-rb were changed by the pull (together with two .txt files and .gitignore).

**Comment by lethosor** [comment]
What was VS complaining about? Sometimes building a second time can help.

**Comment by PatrikLundell** [comment]
Compiling a second time (after restaring VC) did not work. It failed to find protobuf.exe (or a similar exe name) as error 6 out of 6, and I didn't bother go back further to look at other errors in that message flood as that was enough to confirm it wasn't caused by my changes,

**Comment by BenLubar** [comment]
@PatrikLundell are you using Visual Studio through the project generated by the `generate-*.bat` scripts or through the CMake thing I just added support for?

**Comment by PatrikLundell** [comment]
I'm using VS through dfhack.sln (which is what the issue above concerns) as well as install-debug. The dfhack.sln was generated under 0.44.10 (some alpha DFHack version), and so nothing is based on new support I know nothing about, but I guess that can have interfered with the running VS (I hadn't exactly expected my embark-assistant repo to change under my feet...).

**Comment by lethosor** [comment]
Travis actually didn't complain about "NA" not being handled. GCC running on BuildMaster did, but that's because it has additional warnings enabled. We would like to keep the code warning-free, though, so thanks for addressing that too.

**Comment by PatrikLundell** [comment]
I definitely don't like code that results in a bazillion warnings, and I'm definitely prepared to add redundant code to silence warnings. If you keep the code as warnings free as possible, you know a new warning is something you have to address (and the fairly recent change that got rid of deprecated feature warnings was rather helpful). This is one reason I'm less than thrilled with CodeFactor's rather stupid "complexity" warnings. The blank lines rejections were nit-picky, but such blank lines ARE unsightly.

**Comment by BenLubar** [comment]
Occasionally, if the sln breaks, I find it's easiest to just delete the VC2015 folder and generate a new one.

**Comment by PatrikLundell** [comment]
I originally thought it might be const since it unreasonably pointed at local variables, and didn't bother to restore it when that didn't turn out to be what it didn't like.  Logically, complexity ought to be paths and the like, which is why it's odd that it pointed at local variables.
The temperature code is a bit messy, but that's what I've deduced that the logic is.

It might be that complexity is calculated as branches over number of lines or something stupid like that, making chattier code look better.

**Comment by lethosor** [comment]
I don't see https://www.codefactor.io/repository/github/dfhack/dfhack/pull/1362 pointing at local variables specifically. There's this:
image
but it says lines 405-469 (i.e. the whole function), and clicking on it leads to https://github.com/DFHack/dfhack/blob/fdf52deb367df82b88ed4ed36d4f06c6a1a79454/plugins/embark-assistant/survey.cpp#L405-L469, which highlights the whole function.

I suppose I can see how you'd think it's highlighting just the first few lines of the function, which happen to be mostly local declarations, but the "complex method" title and link clued me in to it being the whole function.

Also, this is the number of branches (hovering over complexity) that I was referring to:
image
It sounds like 17 is the number of branches, regardless of number of lines. I haven't bothered to check its math there.

**Pull request merged**
