### PR TITLE
Embark assistant

### PR DESCRIPTION
**Pull request by PatrikLundell**
Changed region interaction matching to search for evil rain, syndrome rain, and reanimation rather than interaction presence (misleadingly called evil weather), reanimation, and thralling. Syndrome rain and reanimation get wider ranges of criterion values.

### CODE REVIEW

**Comment by lethosor** [comment]
Any preference on a changelog entry? Should I just take your comment there (and change its tense)?

**Comment by PatrikLundell** [comment]
I don't have any preferences, so a tense change would work well.
I promised to look at Sphinx, but haven't done more than a fairly quick look at a couple of web pages... Finding out how to do documentation will have to wait until the next time.

**Comment by lethosor** [comment]
The changelog format is actually custom now, but basically RST (like the rest of the sphinx docs). I'll show you what I did once I add it.

**Comment by PatrikLundell** [comment]
I've got a problem with understanding how updating changelog.txt (I've just located the file) would work on an administrative level:
If more or less every pull request changes the file to add its particular change, the file is almost always going to either be conflicting when the pull request is made, or become so not long after when some other pull request is accepted?

**Comment by lethosor** [comment]
That's true, if things are added in the same place in the same subsection, and I had to resolve conflicts in some of @suokko's PRs for that reason. Fortunately, for one-line add/add conflicts like that, GitHub's "resolve conflicts" button in the web UI works well. I'm not sure if that's something you would have access to or if it's limited to repo maintainers.

**Pull request merged**
