### PR TITLE
Not all stockpile items being returned for getStockpileContents.

### PR DESCRIPTION
**Pull request by silverflyone**
Changed the StockpileIterator::operator++ to checks blocks based on <= 16 rather than <16. Previously the iterator was not returning items at stockpile tiles at the block boundary. Identified as part of combine.lua changes.

### CODE REVIEW

**Comment by silverflyone** [comment]
@myk002: https://github.com/DFHack/scripts/pull/618 needs this change.

**Comment by myk002** [comment]
Ack. I'll review in a few hours

**Review by myk002 — APPROVED** [review]

**Comment by myk002** [comment]
could you add a changelog entry under Fixes?

**Comment by silverflyone** [comment]
Updated the changelog.

**Review by myk002 — APPROVED** [review]

**Pull request merged**
