### PR TITLE
Re-enable build of several plugins

### PR DESCRIPTION
**Pull request by lethosor**
Likely to still work, and were probably just disabled due to v50 changes:
- changeitem
- createitem
- deramp
- flows
- lair

and a couple that don't access DF data at all:
- luasocket
- title-folder

### CODE REVIEW

**Comment by lethosor** [comment]
Some basic tests:
- createitem works (with the keyboard cursor: `createitem BAR IRON 20`)
- changeitem works (with a pick: `changeitem m GOLD`, `changeitem q 5`, `changeitem s ITEM_WEAPON_AXE_BATTLE`)
- deramp works (m-x, select ramps, run `deramp`)
- flows works (`flows` produces reasonable-looking output)
- lair works (doesn't crash, `lair` and `lair reset` set the expected occupancy bit on a map block I checked, and don't crash)

**Comment by myk002** [comment]
I'm good for all the others, but I was trying to leave `createitem` out to avoid the functionality overlap with `gui/create-item` and `modtools/create-item`. Could you remind me what the remaining feature gaps are?

tangentially, we could rename `modtools/create-item` to just `create-item` since the interface is less esoteric than it used to be.

**Review by myk002 — APPROVED** [review]
LGTM. [Did you say](https://discord.com/channels/793331351645323264/807444467140788254/1105992483005014127) that `title-folder` was problematic, though?

**Comment by lethosor** [comment]
Disabled title-folder for now.

We talked a bit about it on Discord, but summarizing here for continuity: I feel that including these plugins again, since they work and people have asked (about some, anyway), is preferable to waiting to refactor/rewrite/replace them. For createitem, we are probably pretty close to being able to replace the CLI with a wrapper around the modtools or gui script, but not quite there yet. (Some specific features are the ability to create at an arbitrary cursor position, sans unit, and create items in containers.)

Will update the changelog before merging.

**Comment by myk002** [comment]
re: `createitem` feature parity: autochoosing a creator unit if none is selected/specified is implemented for both `gui/create-item` and `modtools/create-item`. creating at a given position is implemented for `modtools/create-item`. Both tools will currently automatically create an appropriate container for items that need containers, but do not currently support creating in an existing container or building.

**Comment by lethosor** [comment]
My examples are evidently a bit outdated, thanks

**Comment by lethosor** [comment]
@myk002 can you verify that https://github.com/DFHack/dfhack/pull/3360/commits/b6723e4fdbd0a72d766d12d8322ca240632d0ba4 is accurate before I merge?

**Comment by myk002** [comment]
> @myk002 can you verify that [b6723e4](https://github.com/DFHack/dfhack/commit/b6723e4fdbd0a72d766d12d8322ca240632d0ba4) is accurate before I merge?

I believe that's right, and it's correct according to the spreadsheet -- did you do a sync? I must have forgotten to pull those in for the last release.

**Comment by lethosor** [comment]
I did a convoluted search. If you have a better way to sync plugin status, I'd be happy to hear it :)

```
git grep -l unavailable docs/plugins/ | xargs -n 1 basename | cut -d. -f1 | xargs -i -t grep -Ei '#(dfhack_plugin|add_subdirectory)\({}' plugins/CMakeLists.txt 
```

`labormanager` is the only plugin that doesn't have the expected match now, and that's because it was moved to plugins/autolabor/CMakeLists.txt. (it is disabled, and correctly marked as unavailable)

**Comment by myk002** [comment]
shell pipelines are beautiful ; ) the command for syncing the spreadsheet to the docs dir is here: https://docs.google.com/spreadsheets/d/1hiDlo8M_bB_1jE-5HRs2RrrA_VZ4cRu9VXaTctX_nwk/edit#gid=1532003062

**Pull request merged**
