### PR TITLE
Update eventful.lua

### PR DESCRIPTION
**Pull request by warmist**
Had wrong function. Fixes https://github.com/DFHack/dfhack/issues/2202

### CODE REVIEW

**Comment by warmist** [comment]
needs testing

**Comment by warmist** [comment]
tested with:
```lua
local ev=require 'plugins.eventful'

function fcallback( reaction,reaction_product,unit,input_items,input_reagents,output_items,call_native )
	print("=================================")
	print("event callback",reaction,reaction_product)
	call_native.value=false
end

ev.registerReaction("TAN_A_HIDE",fcallback)
```

**Review by myk002 — APPROVED** [review]
Code and doc changes look good. Could you add a changelog entry?

I don't see where the extra space is either. If you make a PR comment that says "pre-commit.ci autofix", then the automation can try to commit a fix for you. Try that and see what it does.

**Comment by warmist** [comment]
pre-commit.ci autofix

**Review by myk002 — APPROVED** [review]

**Pull request merged**
