### PR TITLE
Improved script documentation

### LINKED ISSUE #823: Improve usage and handling of script 'docstrings'
Thanks to Sphinx and some custom code in `conf.py`, documentation for scripts is stored in their source files and built into the docs at compile time.

However, there are two changes I intend to make (pending a some of the pull requests that may clash):

1. Change the marker style for Lua to avoid the use of `=begin` and `=end`.  This will facilitate use of the same string, without any duplication, in online docs, as a top-of-file explanation, and as the help text in the DFHack terminal.

2. Consequential changes, eg updating docs and example scripts, merging any separate helpstrings with docstrings as appropriate, etc.

May cause minor conflict with #722 depending on implementation timing.

Requires #723, as I'm not going to do separate pull requests against all the script subrepos and deal with the pain of it not being synced again!

### LINKED ISSUE #944: GitHub doesn't handle docs/Contributing.rst
Contributing.rst was moved to the docs folder in a5d1211feaa3c2416d9ed53dab5a40fd06d9acb1 (@PeridexisErrant) which broke the banner linking to it when creating a new issue/PR. There are a couple options here:
* Move it back to the root directory. I'm not sure how well this would work with Sphinx, though.
* Move it to a `.github` folder (should work, according to [this](https://help.github.com/articles/setting-guidelines-for-repository-contributors/))
* Symlink either of those paths to docs/Contributing.rst - this could cause issues if anyone tries to modify it on Windows, and I don't know for sure if GitHub will handle it.

Thoughts?

### PR DESCRIPTION
**Pull request by PeridexisErrant**
Merged in-console help with Sphinx docs in most cases, cleaner tokens, fixed typos etc, simpler config,  and so on.

Closes #823 and closes #944 too since I was there.

### CODE REVIEW

**Comment by lethosor** [comment]
Gah, this was a bad time for me to do #723, sorry. The changes in `scripts/` look fairly trivial/uncontroversial, so I'll try to merge them into dfhack/scripts. Once I've done that, can you get rid of the scripts changes here and rebase on develop?

**Comment by PeridexisErrant** [comment]
Yep, happy to rebase however needed.  I did rather jump the gun, and against my documented intentions :)

**Comment by lethosor** [comment]
Ok, I got a bit distracted by 022a1bf9e88b51e92f02f3f6a73a12373401d3e8, but the script changes are done in https://github.com/DFHack/scripts/commit/3c3e7a487164f416c93f9eaebca25f9db0019ea2. Rebasing the rest on develop would be great.

**Comment by PeridexisErrant** [comment]
I suspect a stuffup with the new submodule not appearing or something, but don't have time to debug it right now.  I'll have another look tomorrow, if you can't tell what's wrong.

**Comment by lethosor** [comment]
7156b3c might fix it.

**Comment by lethosor** [comment]
Looks like sphinx can handle `=begin`/`=end` markers in scripts, but `script-in-readme.py` can't. I'll update the rest to use the new markers.

**Comment by PeridexisErrant** [comment]
Can you rerun the travis build, since you've got write access?

**Comment by PeridexisErrant** [comment]
OK.  I'm having *unrelated* problems getting the scripts submodule to work on my machine; this build works - Travis is failing on a rst syntax error in dfhack/scripts@40cf4ae2.  

Still, this at least *reduces* the number of submodules for scripts to go wrong in!

**Pull request merged**
