### PR TITLE
adjust price of vermin swarms

### PR DESCRIPTION
**Pull request by myk002**
divide by 10000

### CODE REVIEW

**Comment by quietust** [comment]
I don't believe this is correct - DF's item value code doesn't have a special case for vermin colonies, just `PETVALUE_DIVISOR` which happens to be 1000 for honey bees.

**Review by quietust — CHANGES_REQUESTED** [review]
Change is incorrect - the actual game only checks `petvalue_divisor` and does not check the VERMIN_SOIL_COLONY flag at all.

**Comment by myk002** [comment]
So the issue here is then that bees have a matgloss of -1, which cannot be used as a caste index. What should I do exactly in that case?

**Comment by quietust** [comment]
In that case, the game itself uses caste 0 instead, which it looks like we're now doing.

**Pull request merged**
