### PR TITLE
uicommon cleanup

### PR DESCRIPTION
**Pull request by BenLubar**
This should get rid of a lot of the warning messages.

### CODE REVIEW

**Comment by lethosor** [comment]
I'm not sure what the benefit of getting rid of for_each_ and transform_ is - they're more concise than the standard library functions they wrap.

**Comment by BenLubar** [comment]
We probably don't even need to use `for_each` or `transform` - all of the places they're used are simple 1-line callback functions that could just be part of a `for` loop.

**Comment by lethosor** [comment]
Sure, but for_each and transform make it clearer what types are being iterated over and get rid of some cruft, like referencing the same container multiple times, (*it)->foo, etc.
If there are warnings related to these, fixing them is fine, but I don't think using for_each and transform is incorrect.

**Comment by expwnent** [comment]
I agree with @lethosor. I like it better with `for_each` and `transform` unless they're causing warnings. The static -> inline stuff would be good though.

**Pull request closed without merging**
