### PR TITLE
Kloker - manipulator forked.

### PR DESCRIPTION
**Pull request by strainer**
Here is my manipulator fork. I have rebranded along with a load of new features and tweaks, and git renamed to keep commit history and allow manipulator.cpp to remain for those prefering it. It would be great if dfhack could receive this back as users at bay12 have appreciated it and its seems quite well tested and stable by now. I should be around to maintain it for structure changes and any fixes required.

### CODE REVIEW

**Comment by quietust** [comment]
This cannot possibly be merged as-is - at the very least, commit b4f4f2b537b097d6ee8fcb95bad7603f7b27dc4e must be removed (since it basically erases the entire DFHack repository), and all of the binary artifacts you added will need to be removed as well.

**Comment by strainer** [comment]
Ah sorry I thought it possible to just merge in the file kloker.cpp to \plugins\

**Comment by strainer** [comment]
I suspect it is not difficult for a maintainer to just cherry pick my pull and only take in kloker.cpp but I can try and make a simpler pull if necessary. 
Development of manipulator.cpp seems to have stopped several years ago with no bugfixes or new features but some users seem perfectly content with it also, so Im not wishing to rename or put an end to manipulator.cpp. There is also manipulator.lua which is almost feature parity with manipulator.cpp. Kloker is a really big fork of manipulator.cpp, its got lots of extra features and has a different feel. It contains about half of manipulators code, and about 5kloc of my own code which is over 75% of the overall plugin. It feels very reasonable to return it to dfhack as a fork with its own name, features and character. The two plugins can run side by side, dfhack may leave kloker disabled if desired, but it would be very useful to me and to enthusiastic kloker users if dfhack could receive this dfhack plugin which a great deal of passionate work has gone into creating for the dwarf fortress community. Have you played it Quietus? I had hoped you would like it.

**Comment by ab9rf** [comment]
There are 191 commits changing 785 files in this pull request. It's not even remotely reasonable for us to try to sort through all that to try to figure out what has value and what does not. Please make a clean PR from a clean rebased repo, and resubmit.

I strongly recommend that this be closed. If the PI wants to resubmit the pull request from a cleanly rebased fork we can discuss it in more detail.

**Comment by lethosor** [comment]
It is certainly _possible_ for us to just copy in kloker.cpp from this branch. The issue with doing that is that we'll lose git history, which will make it harder to merge in any future changes that you make, particularly if changes are made in the DFHack repo as well. One of the things that git does very well is merging changes from multiple sources, but it needs a common ancestor to do that, which we wouldn't get by manually copying in the file. (And as mentioned above, merging this PR as-is would also apply your commits that delete the rest of the DFHack repo, which isn't an option.)

It might be possible to start a new branch based on DFHack's develop branch and use `git filter-branch` or something similar to apply just changes made to kloker.cpp. `git cherry-pick` repeatedly is another (more painful) option, as is just copying the final kloker.cpp into a new branch (in which case you would need to continue development on that new branch, without previous history, in order to merge in future changes).

As a side note, there was some confusion on IRC about what the "Kloker" name means, as well as some of the terminology used in the plugin itself. Most of our plugins/scripts have fairly self-explanatory names. Some documentation (docs/Plugins.rst) might also be useful.

**Comment by strainer** [comment]
Thanks for comments and sorry about the kloked up PR. 
From stackoverflow, it seems its possible for me to fetch and checkout dfhacks latest develop branch and then just checkout kloker.cpp from my 'master' branch.

A kloker is a name for a cave sprite like a kobold known to miners that makes mysterious knocking noises near interesting seams. To 'clock' or klock something is also slang in some places for noticing something. Perhaps its not dfhack style, I felt it a cute fanatasy name. Cavern Keeper could be more explanatory. As this plugin gives a very detailed view of dwarf personalities and conditions it is no longer 'just' a labor manipulator.
 
Some terms used to describe dwarf personalities are challenging english, but they were refined by multiple players in a topic on reddits dwarf fortress. I spent days and days obsessing over them myself, reading the docs on the traits and searching thesaurus, but with so much character traits to summarize with polarised terms for high or low values - it seems some confusion/mystery/ambiguity is unavoidable. 
I could work on a section for plugins.rst, but surely that's not a hold up for having the plugin taken so it can get compiled and played by current users. There seem to be some plugins in development without much documentation.

An example of an existing bug in manipulator.cpp is that dwarfs on military service show up as 'idle' in the activities column. That caused me some confusion when I was trying to arrange active military. Kloker just manages to show "On Duty" for active military, getting the exact activity seems tricky. Also manipulators controls of the sorting system are so awkward as to be an issue, to me. Maybe its not awkward compared to dwarf fortress menus, but dfhack has many tweaks to help smooth the situation. Manipulators profession masks cant be made without text editing the files, and professions cant be removed without manual deleting in the folder. Issues like these made it seem unfinished to me. Kloker is developed to be as pleasant as possible to read and navigate and feels quite finished. If the dfhack hive mind feels like changing things after pulling it, all I will be able to do is appreciate or lament them...

**Comment by lethosor** [comment]
If you want help setting up a new branch with just your commits to kloker.cpp, I could help with that. (I haven't looked into exactly what would be required yet, but we've done similar things in the past, e.g. moving scripts to their own repo.)

Regarding the end of your last message: I know you think it's feature-complete, but once a tool is in the DFHack repo, there's a decent chance that people will submit bugfixes/improvements/other changes here. If we want to be able to merge those in *and* any future changes that you make, we'll need a shared commit history between this repo and yours. That's why I'm hesitant to just copy the plugin in and would prefer to have your changes in a new branch based on our develop. (Also, reviewing the code here is somewhat difficult, and a new branch with just the relevant changes would make that easier.)

I don't think I mentioned this here yet, but another option is setting up a separate [buildmaster](https://buildmaster.lubar.me/) project for this plugin, which would give you automatic builds without needing the plugin in this repo. A handful of third-party plugins do that already: df-ai, weblegends, dfplex, and maybe others I'm forgetting.

**Comment by strainer** [comment]
Buildmaster is tempting but I am keen to get this to dfhack as it would be awesome to see continued develpment. I may argue that reverts of some of my design choices would be regressions, (like my 'forbade/availed' labors instead of 'disabled/enabled') but i'd get over it, make a custom version if bugged enough. I've just scratched most of my own itches at this stage. A potential name that would be less fantasy than kloker and much more Hack could be "groker" or "DFgrok" ? 
My repo is pretty munged at the moment, if I can find a tool or basic instructions to follow I dont mind if I need to do hundreds of steps or 'cherry-picks' in order to create a pullable kloker branch with history on the file. Lots of my old commits should be combined anyway due to trivial whitespace edits and things so I really should get around to groking git enough to do that.

**Pull request closed without merging**
