### PR TITLE
Included 64-bit build of libruby1.8.7 for linux

### PR DESCRIPTION
**Pull request by dseguin**
Built from https://github.com/ruby/ruby on branch ruby_1_8_7

Changes:
  - Added 64-bit libruby for linux
  - Changed ruby/CMakeLists.txt accordingly
    - Default behavior is the same (unpack 32-bit lib)
    - When `DFHACK_BUILD_ARCH`=64, it unpacks the 64-bit lib

### CODE REVIEW

**Comment by lethosor** [comment]
Thanks for building this! Sorry for not responding earlier - I was busy with OS upgrades.

I'm looking to move away from storing binaries in this repo (our current/temporary? solution is dfhack/dfhack-bin), but I will add it there as soon as I get a chance, and update ruby/CMakeLists.txt accordingly (and add you to Authors.rst if you don't mind).

**Comment by dseguin** [comment]
Hmm, maybe it would be better to add ruby as a submodule? Also, I forgot to strip the debug symbols, so the lib is larger than it should be. I think `strip --strip-unneeded <lib>` will reduce it by ~2/3.

> (and add you to Authors.rst if you don't mind)

Thanks, but I haven't contributed any code ;) (But yes, you can add me)

**Comment by lethosor** [comment]
Ruby takes a lot longer to build than Lua (and we don't modify it), so it's nice to have pre-built binaries. Feel free to reduce the size of this one if you like.

**Comment by dseguin** [comment]
Gotcha. Whenever you have time, you can merge this or copy the lib to dfhack/dfhack-bin, whatever works.

**Comment by lethosor** [comment]
(Never mind, mixed this up with #987.)

I still need to handle this - sorry for the delay. Just checking: you've tested this (e.g. `multicmd`) on 64-bit Linux 0.43.05, yes?

**Comment by dseguin** [comment]
Yes. Tested just now with a fresh clone.

**Comment by lethosor** [comment]
Merged (sort of). Thanks!

**Pull request closed without merging**
