### PR TITLE
New Plugin:blueprint

### LINKED ISSUE #479: Replace `needs_porting/copypaste.cpp` with a Quickfort blueprints generator
The original plugin was designed to copy a section of the fortress to another section.  

I believe that generating blueprints is a better way to go though; as it's less 'cheaty', allows multi-fort usage and sharing, and the blueprints can be implemented with other tools (eg digfort and fastdwarf).

The command would be something like `make-blueprint <volume> <plan_name> [dig [build [place [query]]]]` (see [QF syntax](http://www.joelpt.net/quickfort/#editing-blueprints)), and the script would output the blueprint for the corresponding phase or phases.

The dig phase would read the shape of rooms to carve out, and the blueprint could be implemented by `digfort.rb`.  The build phase would place all buildings, furniture, and constructions, and the blueprint might be implemented by the new `fortplan` plugin.  The place phase records stockpiles, and would have to be implemented by Quickfort.  The query phase records created rooms and is likewise not yet possible with DFHack.

These could be implemented in stages, and would be a giant leap for fortress construction techniques - a way to eliminate the complex and tedious process of writing a blueprint.  Instead you could just decide to record something you like!

### PR DESCRIPTION
**Pull request by cdombroski**
Fixes #479 

The base functionality is here, but I'll probably do a few more commits to clean up how the phase list in the parameters is handled and how buildings and stockpiles are written out.

### CODE REVIEW

**Comment by PeridexisErrant** [comment]
This is very exciting - I'm watching with great interest.

**Comment by cdombroski** [comment]
Unless somebody breaks it or has another idea, I've finished working on this now.

**Comment by expwnent** [comment]
Merged manually.

1. fixTexts should be run once before releases. It keeps the repo smaller that way.
2. Please do PRs targetted at DFHack:develop instead in the future.

**Comment by expwnent** [comment]
I had to fix [this compilation bug](https://github.com/DFHack/dfhack/commit/53a8032f8af30ae668bcf27e44474b7e6667180d) to make it compile on linux. Be aware of that for the future.

**Pull request closed without merging**
