### PR TITLE
DataIdentity support for new types (std::mutex, std::condition_variable)

### PR DESCRIPTION
**Pull request by lethosor**
Requires https://github.com/DFHack/df-structures/pull/622
Needed to fix enabler on Linux (#3427)

### CODE REVIEW

**Comment by lethosor** [comment]
I think this should work now. Needs testing on Windows to be sure.

**Comment by lethosor** [comment]
enabler still appears to be aligned on Windows. Merging.

**Review by myk002 — APPROVED** [review]
I'm not an expert in everything that was changed here, but it all looks reasonable. and proof that windows still works gives me some confidence

**Comment by lethosor** [comment]
I'm not too worried either. Just wanted to make sure I didn't accidentally introduce a misalignment. ab9rf also confirmed that gps is the correct size still. 

On the DFHack side (this PR), most the changes are either strict additions, or changes to Lua wrappers for types that shouldn't generally be accessed from Lua anyway (std::fstream).

**Pull request merged**
