### PR TITLE
Update announcement code to v50.11

### LINKED ISSUE #3476: autoDFAnnouncement opens the embark message for all types
Hi, the dfhack.gui.autoDFAnnouncement method seems to treat all types as embark announcement (the Strike the Earth! message).

I tried to simulate a job cancellation using this function:

```
function CancelReaction(reaction, unit, input_reagents, reason)
    local message = string.format(
        "%s, %s cancels %s: %s.",
        dfhack.TranslateName(dfhack.units.getVisibleName(unit)),
        dfhack.units.getProfessionName(unit),
        reaction.name,
        reason 
    )

    dfhack.gui.autoDFAnnouncement(df.announcement_type.cancel_job, unit.pos, message, COLOR_YELLOW)

    for _, v in ipairs(input_reagents or {}) do
        v.flags.PRESERVE_REAGENT = true
    end
end
```

I tried with other types, such as stuck_minerals or combat messages. It does write an entry in gamelog.txt, however.

Thanks

### PR DESCRIPTION
**Pull request by Bumber64**
Update announcement code based on reverse engineering of v50.11 (win64 Steam)
* Updated announcement functions to use alert system and `markup_text_boxst`
* Add versions of combat report functions that take `report *`
* Default parameters for Lua API functions
* Alphabetized include statements

Closes #3476

### CODE REVIEW

**Comment by Bumber64** [comment]
More stuff:
* Announcements print non-parsed text outside of the popup. Bay12 issue: https://dwarffortressbugtracker.com/view.php?id=12671
* How should `showAutoAnnouncement` differ from `autoDFAnnouncement`? Should the former play announcement sounds?
* Get some of these functions (`MTB_Parse`, `MTB_Prepare`, `autoDFAnnouncement`) as global functions from Bay12?
* Update Lua API doc and changelog.txt

**Comment by Bumber64** [comment]
Since I'm not implementing the `meeting_context` dipscript functions, I'll just report on how the tokens work here.

`meeting_context_setColor` sets text color based on a dipscript variable. For units, this is Magenta for fort units, Red for hostiles, or `entity_raw.friendly_color` (default Cyan) for non-hostile (including invader parley.) It can also get a color from an `active_script_varst`.

Valid tokens: `[C:VAR:DIPEV:DIPLOMAT]`, `[C:VAR:DIPEV:ASSOCIATE]`, `[C:VAR:MEETING:ACTOR]`, `[C:VAR:MEETING:NOBLE]`, or  `[C:VAR:DIPSCRIPT:<active_script_varst.name>]`.

---
`meeting_context_formatString` outputs a string based on `format`. Token looks like `[VAR:<format>:<var_type>:<var_name>]`.

`<format>` is one of `NATIVENAME` (valid for unit, entity, or plot_info spec refs,) `TRANSLATEDNAME` (unit, entity, or plot_info,) `TITLENAME` (unit,) `HISTNAME` (hist_fig spec ref,) or `NAME_PLURAL` (creature_def.) It will be ignored for value (int32_t) types.

`<var_type>:<var_name>` are:
`GLOBAL:DIPLOMACYFLAG_SUCCESS` (int32_t 0x4)
`GLOBAL:DIPLOMACYFLAG_FAILURE` (int32_t 0x2)
`GLOBAL:YOURCIV` (entity spec ref)
`GLOBAL:YOURFORT` (plot_info spec ref)
`GLOBAL:TREESREMOVED` (int32_t)
`GLOBAL:NULL` (null spec ref)
`GLOBAL:LOCAL_LARGE_PREDATOR` (creature_def spec ref)
`GLOBAL:RANGE.<min>.<max>` (random int32_t in range min, max inclusive)
`DIPEV:DIPLOMAT` (unit spec ref)
`DIPEV:ASSOCIATE` (unit)
`MEETING:ACTOR` (unit)
`MEETING:NOBLE` (unit)
`DIPSCRIPT:<active_script_varst.name>` (depends on var)

**Comment by myk002** [comment]
> * How should `showAutoAnnouncement` differ from `autoDFAnnouncement`?

The docs say:
`If you want a guaranteed announcement without parsing, use dfhack.gui.showAutoAnnouncement instead.`

Is that still accurate?

**Review by myk002 — COMMENTED** [review]
overall, looks good, and testing shows it functioning properly

Could you update changelog.txt. Also, are any doc updates needed in Lua API.rst?

**Comment by Bumber64** [comment]
> > * How should `showAutoAnnouncement` differ from `autoDFAnnouncement`?
> 
> The docs say: `If you want a guaranteed announcement without parsing, use dfhack.gui.showAutoAnnouncement instead.`
> 
> Is that still accurate?

Other than the parsing part. That's been moved into `showPopupAnnouncement` since it needs to be done to build the `markup_text_boxst`. `autoDFAnnouncement` also contains debug output so you can know why it failed. We might have it not do announcement sounds if we get around to implementing that. I've updated the docs, which now also tells you how to enable the debug printing.

**Review by myk002 — APPROVED** [review]

**Pull request merged**
