### PR TITLE
Update the rendermax plugin with warmist's changes

### PR DESCRIPTION
**Pull request by Clyybber**
Warmists updated version contains some optimizations

### CODE REVIEW

**Comment by Clyybber** [comment]
Will probably need to remove the whitespace after the comment in renderer_light.cpp at line 1327 to make travis-ci content. It built successfully though.

**Comment by warmist** [comment]
So okay i must comment why I haven't issued a pull-req:

- Not sure if it's faster for everyone and how much faster
- It has a TODO and i'm not sure if it's implemented
- It still needs a sun propagation rewrite, which would move the sunlight to threaded part of work
- MOAR profiling just to see what it slow
- I'm not sure if i like how it looks.

So it can be merged in but i'm hoping for some more work by someone?

**Comment by warmist** [comment]
So sorry to do this, but i've made another branch which will use opencl with rendermax. Hopefully that will increase the fps for everyone :)

**Comment by Clyybber** [comment]
No problem, thank you for your work!

**Pull request closed without merging**
