### PR TITLE
Add updated emigration script, gui/family-affairs

### PR DESCRIPTION
**Pull request by PeridexisErrant**
Emigration was one of the classic scripts for 34.11, and now it works for 40.24 too - if in somewhat simplified form.

gui/family-affairs is adapted from the script by Raidau, and allows you to add or remove romantic relationships between dwarves.

### CODE REVIEW

**Comment by PeridexisErrant** [comment]
If anyone knows how to stop remotefortressreader breaking unrelated builds, that would be lovely.

**Comment by lethosor** [comment]
It's breaking because Japa pushed a change that doesn't compile.

**Comment by JapaMala** [comment]
Sorry about that.
From the next release, I'm going to stick with a branch until it's time to
merge.
Should be fixed now anyway.

**Comment by lethosor** [comment]
@Japa, You're not the first person who's forgotten to add a df-structures change :) I wouldn't worry too much about branching for RFR, although it's not a bad idea to make a PR for large changes and make sure it passes.

@PeridexisErrant The build is passing now. I'll take a look at this (and the other two open PRs) shortly.

**Comment by PeridexisErrant** [comment]
@JapaMala - no worries, we all know it's for a good cause :)

**Comment by fricy** [comment]
The emigration script needs some love:

     [DFHack]# emigration enable
    Emigration enabled.
    ..../Macnewbie/Dwarf Fortress/hack/scripts/emigration.lua:63: attempt to index global 'u' (a nil value)
    stack traceback:
        ....18/Macnewbie/Dwarf Fortress/hack/scripts/emigration.lua:63: in function 'canLeave'
        ....18/Macnewbie/Dwarf Fortress/hack/scripts/emigration.lua:84: in function 'checkForDeserters'
        ....18/Macnewbie/Dwarf Fortress/hack/scripts/emigration.lua:107: in function 'checkmigrationnow'
        ....18/Macnewbie/Dwarf Fortress/hack/scripts/emigration.lua:112: in function 'event_loop'
        ....18/Macnewbie/Dwarf Fortress/hack/scripts/emigration.lua:120: in function 'loadEmigration'
        ....18/Macnewbie/Dwarf Fortress/hack/scripts/emigration.lua:128: in function 'f'
        ./hack/lua/dfhack.lua:555: in function <./hack/lua/dfhack.lua:496>
        (...tail calls...)

**Comment by lethosor** [comment]
There are also some issues with gui/family-affairs (including mismatched variable names, like the above issue).

**Pull request merged**
