### PR TITLE
Allow canceling lineedit with ctrl+c

### PR DESCRIPTION
**Pull request by suokko**
@lethosor Is this closer to behavior you expect from lineedit?

Windows seems to not to support ctrl+c at the moment.

### CODE REVIEW

**Comment by lethosor** [comment]
Ctrl-c in liquids and tiletypes still exits to the DFHack prompt. Ctrl-C in Lua gives a new Lua prompt, though. I'm not sure why that would happen - from reading the code, it looks like the -3 return value should be passed through Console::lineedit properly, but I don't have a lot of time to investigate right now.

**Comment by suokko** [comment]
It should have worked for liquids and tiletypes (at least they worked for me). But I noticed other bugs:
* console returning strings and RETRY or SHUTDOWN.
* The dfhack core prompt not handling RETRY.
* Too many magic numbers. I decided to change return values to constants.
* A few more cases which probably should support RETRY.

**Comment by lethosor** [comment]
I still have the same issue, and will try to investigate. +1 on the constants, though.

**Comment by suokko** [comment]
You could try setting break point on Console::lineedit return line (gdb "b Console-posix.cpp:941") Then I could see the returned string from the std::string passed as reference parameter and I could print the return value (or use finish to return and print the value).

**Pull request merged**
