### PR TITLE
Update windows build scripts

### PR DESCRIPTION
**Pull request by RosaryMala**

### CODE REVIEW

**Review by ab9rf — COMMENTED** [review]
note that all of this is already covered in #2504 

also there's no VC2022_32 folder yet because there is, as of yet, no need for a Win32 build, as there are only 64-bit version of DF so far

**Review by myk002 — APPROVED** [review]
Approved, but I'll leave it to @ab9rf to merge since she's made modifications too

**Comment by RosaryMala** [comment]
That'll teach me to do stuff without first checking other people's repos first.

**Comment by myk002** [comment]
Prolly want to merge into ab9rf's fork, not here.

**Comment by RosaryMala** [comment]
That fork already has everything, so I'm gonna close this.

**Pull request closed without merging**
