### PR TITLE
Documentation formatting, eg internal links

### PR DESCRIPTION
**Pull request by PeridexisErrant**
This is a follow-on pull from #693, which overhauled the organisation and build system for DFHack documentation.

This one:

* Adds internal hyperlinks wherever I found a reference; there's certainly more but this is a good start
* Fixes line length in many places for readability as raw text
* Adds basic formatting to LICENSE , without changing the overall structure or any substantive content (ie just markup)
* Added draft standards for documentation
* Started standardising markup for eg plugin arguments, monospace font
* Adds df-structures documentation
* Adds 3rdparty script documentation (via globbing, so it's automatic if more repos are added)

It's a smaller changeset than the last one, and represents the low-hanging polish that Sphinx lets us add to the docs.  Further work will take some more effort, but there's an example now too.

The changes are again visible at http://peridexiserrant.neocities.org

### CODE REVIEW

**Comment by PeridexisErrant** [comment]
* Added many more internal links
* Checked for undocumented plugins, and added them
* Formatting is reasonably consistent
* Generated HTML uses the DFHack icon, because what else is it for?

Things for someone else to do:

* @expwnent is sorting out the build process and getting DFHack onto readthedocs.org (sorry if this pull makes your life harder), which will make everything viewable online.  We should put a link to that in the root README.rst for users who turn up to GitHub.

* We need some coherent way of categorising plugins.  This should probably be looked at by someone fluent in cpp, at about the same time as Sphinx autodoc is considered - nobody wants to do that work twice.  Tying togther the help system, `ls`, and autodoc is probably a good idea to reduce duplication.

* The lack of autodoc support for ruby and lua [can be worked around](https://github.com/PeridexisErrant/dfhack/commit/8306fc07e776848ca602306f796c9e65bfd24dab).  However we probably want to tie this into the builtin``help commandname``, possibly by having it print a multiline string in the file with a special name (between the identifying points, etc).  I'm happy to do the grunt work on this if someone sets up the general system.

**Comment by PeridexisErrant** [comment]
Rebased onto develop to get the newer build system and third party scripts etc.

I then discovered that my perl install had broken, fixed that, discovered other problems, fixed the VS2010 install, registered, product key, still not working.  I have no idea what's going wrong, but it shouldn't be this difficult.

A `docs/build-docs.[sh|bat]` script might be useful for many users, who want to rebuild the documentation but don't need to compile everything.  It's pretty common for eg script authors, and removes a couple of big dependencies for them.

**Comment by expwnent** [comment]
Is there a reason you rebased instead of merged?

**Comment by PeridexisErrant** [comment]
Nothing beyond recently having had to rebase branches for work - not a good reason, I just ran ``git pull --rebase`` without thinking much about it.  I could probably reconstruct the history in some other way if you'd prefer.

**Comment by expwnent** [comment]
I would prefer it without the rebase if it's not too much work.

**Comment by PeridexisErrant** [comment]
Yep, can do.  Other than that I'm done with this pull request.

**Comment by expwnent** [comment]
Sorry if I misunderstood: are you going to go back and do it all without the rebase?

**Comment by expwnent** [comment]
I think you can start with a fresh branch that's pointing at dfhack/develop and rebase onto that. It should just be a few commands if you do it right.

**Comment by PeridexisErrant** [comment]
Alright, everything's clean and ready at the fresh [documentation-updates](https://github.com/PeridexisErrant/dfhack/tree/documentation-updates) branch.

The only tiny niggle is that in the movement of `conf.py` (or something related), Sphinx for some reason can't find `dfhack-icon.ico` to use as the html favicon.  Simply adjusting the path in `conf.py.in` didn't work, so I'll leave that to you.

**Comment by expwnent** [comment]
Thanks!

**Pull request closed without merging**
