### PR TITLE
reenable `forceequip`

### PR DESCRIPTION
**Pull request by ab9rf**
Looked into this based on discord discussion, determined that the code compiles if adjusted to comport with @Bumber64's changes from #4824 so the question at this point is whether it works which I don't have enough information to evaluate

### CODE REVIEW

**Review by myk002 — COMMENTED** [review]
remember also to add a line to New Tools in the changelog and update forceequip.rst (at least the tags, which should no longer be "unavailable")

Tags in the spreadsheet are:

```
adventure fort animals items military units
```

but that classification might need updating. is `animals` actually appropriate?

**Comment by ab9rf** [comment]
yeah i was holding off on the administrivia until i get some intel that this actually works

**Review by myk002 — APPROVED** [review]
assuming it works, code looks ok

**Comment by ab9rf** [comment]
> assuming it works, code looks ok

i got assurances on discord from a couple of testers that it worked, which is good enough for me given the nature of the tool

**Pull request merged**
