### PR TITLE
Add dfhack.gui.getCursorPos() to Lua API

### PR DESCRIPTION
**Pull request by Bumber64**
Equivalent to ``xyz2pos(pos2xyz(df.global.cursor))``

### CODE REVIEW

**Comment by myk002** [comment]
How is this different from guidm.getCursorPos()?
https://github.com/DFHack/dfhack/blob/e813301d168c1d3d27e2dad1fbe8edf0c2a381d5/library/lua/gui/dwarfmode.lua#L93

**Comment by lethosor** [comment]
The only difference I see is the behavior when `x == -30000`.

However, I'm inclined to say that the existing function is sufficient for the purposes of most scripts. `copyall(df.global.cursor)` should be sufficient for anything else that needs a Lua table. `copyall()` would convert any DF object to a Lua table, so I'm not really sure that we need a special-purpose function to do the same just for the `cursor` global.

**Comment by Bumber64** [comment]
> How is this different from guidm.getCursorPos()?
> 
> https://github.com/DFHack/dfhack/blob/e813301d168c1d3d27e2dad1fbe8edf0c2a381d5/library/lua/gui/dwarfmode.lua#L93

I assume that requires an import or something, because I can't just use it from DFHack's Lua interpreter.

If ``copyall(df.global.cursor)`` works, maybe the examples in "Lua API.rst" should use it instead? It's certainly less typing than any other option.

**Comment by myk002** [comment]
> 



> I assume that requires an import or something, because I can't just use it from DFHack's Lua interpreter.

Yes, sorry, the full example would be:
```
local guidm = require('gui.dwarfmode')
local cursor = guidm.getCursorPos()
```

**Pull request closed without merging**
