### PR TITLE
Adding the dwarfvet plugin

### PR DESCRIPTION
**Pull request by NCommander**
dwarfvet is a plugin to fix and enable the built in animal caretaker behavior in Dwarf Fortress. I worked out the mechanics about a year ago, and started work on a plugin, but real life and personal issues got int he way. Now that I'm back in DF, I decided to dust off this project, update it to work against alpha, and fix most of the remaining "alpha" items I had such as crashes on Windows.

As of right now, it works, and works fairly well, though there are edgecases I need more eyes to look at (I can't tell if an animal will ever generate a traction request), and I'd like to know what the possibility is of actually getting this into DFHack officially.

I can add a "pet drop" fort somewhere to help speed up any testing. Here's the original thread on bay12. http://www.bay12forums.com/smf/index.php?topic=150251.0

### CODE REVIEW

**Comment by warmist** [comment]
Very cool. Didn't know that this was possible.

Looks like travis is complaining about tabs:
./plugins/dwarfvet.cpp: Contains tabs: lines 178, 345-346, 488-490, 492-493, 534, 539-541, 546, 548, 550-551, 557-558, 563, 569, 571-577, 579-581, 583-585, 591-592, 594, 596-597, 811

**Comment by NCommander** [comment]
Whoops. Know a tool that can auto-fix that on Windows?

I'll resubmit the pull afterwards. I plan to flush out the plugin a lot more, but the basics work. I do need to figure out how to get Recover Wounded jobs to work. May drop on Freenode in a bit

**Comment by lethosor** [comment]
You can run lint.py with the --fix argument (although you'll need python for it).

**Comment by NCommander** [comment]
Documentation added; given this is my first contribution, is there anything else you'd like to see before possibly merging?

**Comment by NCommander** [comment]
I need to refile this merge request as I did it against develop on my github fork. Sorry about the noise.

**Pull request closed without merging**
