### PR TITLE
Partial correction of issue 1479 and added verbose flag

### PR DESCRIPTION
**Pull request by PatrikLundell**
I've been unable to identify where DF stores information about actual growths on plants, and so the correction only removes plants where growths are out of season, but not those already gathered.

(#1479)

### CODE REVIEW

**Comment by BenLubar** [comment]
@PatrikLundell can you rebase this? I think the merge conflict is confusing GitHub into not making the `refs/pull/1481/merge` pseudo-branch and that's causing BuildMaster to fail.

**Comment by PatrikLundell** [comment]
@BenLubar Sorry, but I'm not sure I understand what you want me to do. My best guess is that it requires a "proper" reference to df-structures, as I just made the change quietust made after my download locally to make things compile (since df-structures isn't actually part of the project I thought it would be sufficient to have the correct contents). My second best guess is that changing the branch from "master" to "develop" after changing the code, but before making a new branch somehow caused git to sulk (and if that's the case copying the changed files, nuking dfhack, and download everything from scratch, changing things in the proper order, and then copy the saved files would probably be the only way I could achieve it, as I certainly don't know the commands to do it nicely).

**Comment by lethosor** [comment]
image

Basically the changes you've made to changelog.txt here conflict with changes that were made on develop after you created this branch. If resolving those on the command line is tricky, you can just undo the change you made to changelog.txt, paste the line here, and I'll add it manually once I merge this. That should get rid of the conflict, at least.

**Comment by lethosor** [comment]
That looks good to me - thanks for handling the merge + fixes! The error from the tests looks like it's `title-folder` which #1482 should address (but it's not something related to your code anyway).

**Comment by PatrikLundell** [comment]
Yes, it was rather obvious complaints about TWBT had nothing to do with the changes.

Merging the changelog file changes was fairly easy, once I found where you'd "save" the changes (and you had to do it twice).

I belong to the obnoxious group of people who think that code should result in no warnings, or you'll eventually get so many of them that you won't see the cases where they're actually relevant. However, butchering the logic to satisfy an arbitrary "complexity" measurement is going too far (and I think we've touched on that one before).

**Comment by BenLubar** [comment]
Yeah, it's safe to ignore test results from BuildMaster right now if you're not working directly on the DFHack unit test suite (which is really tiny at the moment)

**Comment by lethosor** [comment]
> I belong to the obnoxious group of people who think that code should result in no warnings, or you'll eventually get so many of them that you won't see the cases where they're actually relevant. However, butchering the logic to satisfy an arbitrary "complexity" measurement is going too far (and I think we've touched on that one before).

Agreed, and that's why CodeFactor isn't a required check (it doesn't have to pass to merge this PR). It gives useful feedback sometimes, but the current feedback it's giving on this PR isn't that useful. I wish there were a way to make it less noisy, but I haven't figured one out yet.

**Pull request merged**
