### PR TITLE
skin our scrollbars to look and hover like DF's

### PR DESCRIPTION
**Pull request by myk002**
matches DF's style and behavior in both graphics and non-graphics modes.

### CODE REVIEW

**Review by lethosor — COMMENTED** [review]
Looks good in-game. Do we know for sure that the tile IDs are stable?

**Comment by myk002** [comment]
> Looks good in-game. Do we know for sure that the tile IDs are stable?

I can't be "sure" sure, but it's very likely that these ids in particular are stable. DF loads the first thousand textures or so before it loads world or mod textures. You can see the effects of this in the tile browser. Run the browser on the title screen, and there are only a few textures loaded, notably including these. After a world is loaded, there are more than 100,000 textures, but these ids stay the same.

**Comment by myk002** [comment]
I should add that for any textures I reference in DFHack tools, I only select from the "basic" ones loaded pre-world.

**Comment by lethosor** [comment]
Yeah, that's good. Maybe we should build an enum of at least the ones we care about eventually, in case they do shift around some day.

**Pull request merged**
