### PR TITLE
blueprint: write blueprints to blueprints/ subdir

### PR DESCRIPTION
**Pull request by myk002**
Change blueprints plugin to write to the blueprints/ subdir as its root instead of the dfhack root dir. This keeps blueprints organized in a dedicated folder and sets up for the quickfort plugin to read blueprints from this directory in the future.

To enable writing to a subdir that may not exist, blueprint now automatically creates folder trees. E.g. ``blueprint 30 30 1 rooms/dining dig`` will create the file ``blueprints/rooms/dining-dig.csv``). Previously it would fail if the ``blueprints/rooms/`` directory didn't already exist.

Part 1 of many for #499 (implement quickfort)

### CODE REVIEW

**Comment by lethosor** [comment]
I see you've dealt with some compatibility issues - thanks for working through that! We are a bit limited in terms of C++14/17 features - we could probably bump the Linux compiler up to GCC 5 or 6 by now, but MSVC 2015 is a hard requirement on the Windows side.

Is this at a point where you'd be okay with merging it? Multiple isolated PRs are fine with me (maybe preferred, even) but I don't want to merge something too soon.

**Comment by myk002** [comment]
Thumbs up for review and merge.

I prefer small, incremental PRs as well. It's much easier to get focused feedback and make corrections before wasting too much time going down a wrong path. As a reviewer, I also know it's much easier to review a small PR than a huge one : )

What works well for you? Should I leave an explicit "Ready for review" comment? Or is "ready for review" implicit if the buildmaster checks are clean and "WIP" is not in the title?

**Comment by myk002** [comment]
btw, the buildmaster is awesome! -- I was really worried about my inability to test on windows -- especially once I found out I couldn't use the C++11 std::filesystem class

**Comment by lethosor** [comment]
> What works well for you? Should I leave an explicit "Ready for review" comment? Or is "ready for review" implicit if the buildmaster checks are clean and "WIP" is not in the title?

It can vary by PR, author, etc - I would suggest marking PRs as drafts if they're not ready to go (assuming that CI runs on non-draft PRs, which I think it does), and I'll merge non-drafts that are passing.

**Comment by myk002** [comment]
Awesome. Thanks!

**Comment by lethosor** [comment]
FYI, I added mentions to the `mkdir_recursive` addition in a couple places: https://github.com/DFHack/dfhack/commit/0cc6f40bd6bb936665edd4e8f6ca3fb507476796

**Pull request merged**
