### PR TITLE
Add a Lua module for getting a tile's material

### PR DESCRIPTION
**Pull request by milochristiansen**

### CODE REVIEW

**Comment by milochristiansen** [comment]
"Contains trailing whitespace" That's a problem?

Sadly I can't fix it automatically since my editor lacks a function to trim that... I'll have it fixed in a second regardless.

**Comment by milochristiansen** [comment]
OK, I give up. I got most of it, but somewhere there lurks a byte or two of whitespace at the end of a line.

**Comment by milochristiansen** [comment]
OK, that got it.

I did what I should have done the first time (and would have done had I thought of it), do a search for " \n" and hammer replace until it reports 0 replacements...

**Comment by dscorbett** [comment]
You can squash your commits together:
```sh
git checkout tile-material &&
git reset --soft HEAD~4 &&
git commit --amend --no-edit
```

**Comment by milochristiansen** [comment]
How can I do that without git installed on my system? This laptop is strictly an internet shuttle, I don't want to install git on it.

**Comment by dscorbett** [comment]
I don’t think you can squash through the GitHub interface. The maintainer who merges this pull request can, if they want, squash the commits when merging, [if that is enabled for this repository](https://help.github.com/articles/merging-a-pull-request/#merging-a-pull-request-using-the-github-web-interface).

**Comment by lethosor** [comment]
Yeah, it is, and I'm fine with cleaning it up.

**Comment by lethosor** [comment]
Anyway, I thought you said this was part of the C++ Materials module, but only some of that is exposed to Lua (dfhack.matinfo). Would it be better to expose more of that to Lua and implement whatever can't be exposed as part of the matinfo/materials module on the Lua side? I'm not sure if a dedicated module for getting a tile's material is the way to go.

**Comment by milochristiansen** [comment]
Since no one seemed to want to add bindings for the C++ module I decided to write my own Lua version. Unsurprisingly other people started using it, so with no C++ solution on the horizon I decided to submit my Lua version...

Sure, a set of bindings for the Materials module would be nicer, but it doesn't seem to be happening (while this is done and ready to go).

**Comment by lethosor** [comment]
Yeah, I'm okay with that. We can look at restructuring it when/if someone gets around to wrapping the Materials module.

One thing missing is docs from `Lua API.rst`. It looks like the comments in the lua file should be good, though. I should have time to get to this this weekend.

**Pull request merged**
