### PR TITLE
update quickfort docs

### PR DESCRIPTION
**Pull request by myk002**
default dig
notes blueprints
buildingplan

### CODE REVIEW

**Review by lethosor — APPROVED** [review]
This reminded me that I wanted to switch to "proper" RST section links in #1661 instead of raw links to sections (starting with `#`). Switching would have a couple advantages, like triggering errors if a section name changes and working in the PDF build (I think).

I'll deal with that once I get this and #1667 (and any others) merged in, though.

**Comment by myk002** [comment]
> I'll deal with that once I get this and #1667 (and any others) merged in, though.

No more major doc updates planned in the immediate future.

**Comment by lethosor** [comment]
Ok, I took care of that in 2fdd6f7a (and corrected `messages()` to `message()` in two places, which is hopefully correct - only the latter appears in the source code).

**Comment by myk002** [comment]
Thanks! And yes, "message" is correct.

**Comment by lethosor** [comment]
Another semi-related point: I noticed that code blocks were all being highlighted, so I made some changes - code blocks use a custom syntax that basically just recognizes `#` as a prefix for comments. This doesn't affect the Quickfort guide much, but if you want these snippets to all be just plain text, either a `.. code-block:: text` directive in front of each or `.. highlight:: text` at the top of the page would do it. (I didn't see any actual code blocks in this page, but I might have missed one.)

image

**Comment by myk002** [comment]
I'll keep that in mind, but just from the example you posted above, I'm thinking a bit of color actually makes the blocks a little easier to read : )

**Pull request merged**
