### PR TITLE
Enable ycmd for DFHack

### PR DESCRIPTION
**Pull request by kazimuth**
Enables autocompletion while working on dfhack using [ycmd](https://github.com/Valloric/ycmd).

Autocompletion doesn't work when editing files in library/include/df, but you shouldn't be editing those anyway.

### CODE REVIEW

**Comment by BenLubar** [comment]
@kazimuth did you have to do something special for system headers to work? I get this, for example, on catsplosion.cpp:

```
plugins/catsplosion.cpp|6 col 10 error| 'iostream' file not found               
plugins/catsplosion.cpp|15 col 17 warning| using directive refers to implicitly-defined namespace 'std'
/home/ben/df/dfhack/library/include/Error.h|29 col 10 error| 'string' file not found
```

**Comment by kazimuth** [comment]
@BenLubar, that error looks very familiar, I think it's something to do with GCC and clang conflicting. How do you have ycmd configured?

**Comment by BenLubar** [comment]
@kazimuth I'm using default settings except for `let g:ycm_extra_conf_globlist = ["~/df/*"]`. I installed youcompleteme and ycmd from the Ubuntu 16.04 package vim-youcompleteme (version 0+20151025+gitf20c693-1)

**Comment by kazimuth** [comment]
@BenLubar So, ycmd can't find the system c++ include files for some reason, which likely has to do with OS incompatibilities (I only tested on OS X). It could also be compiler incompatibilities, since we're using gcc to actually compile things, but libclang for completions. Can you paste the `:YcmDebugInfo` from one of the broken files?
[YouCompleteMe #303](https://github.com/Valloric/YouCompleteMe/issues/303) might be relevant-ish.

**Comment by BenLubar** [comment]
`vim plugins/df-ai/plan.cpp` from the dfhack folder:

```
Printing YouCompleteMe debug information...                                                                                                           
-- Server has Clang support compiled in: True
-- Clang version: Ubuntu clang version 3.6.2-3ubuntu1 (tags/RELEASE_362/final) (based on LLVM 3.6.2)
-- Flags for /home/ben/df/dfhack/plugins/df-ai/plan.cpp loaded from /home/ben/df/dfhack/.ycm_extra_conf.py:
-- ['-x', 'c++', '-DLINUX_BUILD', '-DLUA_BUILD_AS_DLL', '-DPROTOBUF_USE_DLLS', '-D_GLIBCXX_USE_CXX11_ABI=0', '-D_LINUX', '-Ddf_ai_EXPORTS', '-fvisibility=hidden', '-m32', '-std=c++0x', '-O2', '-g', '-DNDEBUG', '-g', '-Wall', '-Wno-unused-variable', '-fPIC', '-I/home/ben/df/dfhack/depends/protobuf', '-I/home/ben/df/dfhack/depends/lua/include', '-I/home/ben/df/dfhack/depends/md5', '-I/home/ben/df/dfhack/depends/jsoncpp', '-I/home/ben/df/dfhack/depends/tinyxml', '-I/home/ben/df/dfhack/depends/tthread', '-I/home/ben/df/dfhack/depends/clsocket/src', '-I/home/ben/df/dfhack/library/include', '-I/home/ben/df/dfhack/library/proto', '-I/home/ben/df/dfhack/plugins/proto', '-I/home/ben/df/dfhack/library/depends/xgetopt', '-isystem', '/usr/lib/ycmd/ycmd/../clang_includes']
-- Server running at: http://127.0.0.1:33242
-- Server process ID: 16398
-- Server logfiles:
--   /tmp/ycm_temp/server_33242_stdout.log
--   /tmp/ycm_temp/server_33242_stderr.log
```

`:YcmDiags`:

```
/home/ben/df/dfhack/library/include/Hooks.h|33 col 10 error| 'string' file not found                                                                                    
plugins/df-ai/plan.cpp|56 col 1 error| use of undeclared identifier 'plugin_globals'
plugins/df-ai/plan.cpp|57 col 1 error| use of undeclared identifier 'plugin_globals'
plugins/df-ai/plan.cpp|58 col 1 error| use of undeclared identifier 'plugin_globals'
plugins/df-ai/plan.cpp|59 col 1 error| use of undeclared identifier 'plugin_globals'
plugins/df-ai/plan.cpp|82 col 5 error| member initializer 'tasks' does not name a non-static data member or base class
plugins/df-ai/plan.cpp|83 col 12 error| use of undeclared identifier 'tasks'
plugins/df-ai/plan.cpp|84 col 5 error| member initializer 'rooms' does not name a non-static data member or base class
plugins/df-ai/plan.cpp|85 col 5 error| member initializer 'room_category' does not name a non-static data member or base class
plugins/df-ai/plan.cpp|86 col 5 error| member initializer 'corridors' does not name a non-static data member or base class
plugins/df-ai/plan.cpp|87 col 5 error| member initializer 'cache_nofurnish' does not name a non-static data member or base class
plugins/df-ai/plan.cpp|89 col 5 error| member initializer 'map_veins' does not name a non-static data member or base class
plugins/df-ai/plan.cpp|90 col 5 error| member initializer 'important_workshops' does not name a non-static data member or base class
plugins/df-ai/plan.cpp|91 col 5 error| member initializer 'important_workshops2' does not name a non-static data member or base class
plugins/df-ai/plan.cpp|99 col 5 error| member initializer 'map_vein_queue' does not name a non-static data member or base class
plugins/df-ai/plan.cpp|100 col 5 error| member initializer 'dug_veins' does not name a non-static data member or base class
plugins/df-ai/plan.cpp|108 col 5 error| use of undeclared identifier 'tasks'
plugins/df-ai/plan.cpp|108 col 25 error| no matching constructor for initialization of 'task'
plugins/df-ai/plan.cpp|110 col 5 error| use of undeclared identifier 'important_workshops'
plugins/df-ai/plan.cpp|111 col 5 error| use of undeclared identifier 'important_workshops'
```

`vim plan.cpp` from dfhack/plugins/df-ai:

```
Printing YouCompleteMe debug information...
-- Server has Clang support compiled in: True
-- Clang version: Ubuntu clang version 3.6.2-3ubuntu1 (tags/RELEASE_362/final) (based on LLVM 3.6.2)
-- Flags for /home/ben/df/dfhack/plugins/df-ai/plan.cpp loaded from /home/ben/df/dfhack/.ycm_extra_conf.py:
-- []
-- Server running at: http://127.0.0.1:60185
-- Server process ID: 16477
-- Server logfiles:
--   /tmp/ycm_temp/server_60185_stdout.log
--   /tmp/ycm_temp/server_60185_stderr.log
```

**Pull request merged**
