### PR TITLE
WIP adding furnaces to building hacks

### PR DESCRIPTION
**Pull request by warmist**
This (some day will) implements #1366

### CODE REVIEW

**Comment by lethosor** [comment]
How in-progress is this?

**Comment by warmist** [comment]
As noted in #1366 this lacks the support for machine in furnaces. Adding such thing would be very hard. Features that are left might be valuable. Also as is noted in code - there could be use from adding furnace specific features (afaik only melted metal fractions is unique to furnaces).

Today i've commited last part that was missing. So what is left is testing (can't remember if i've tested this enough) and doc updates (probably to the new inlined docs)

**Comment by lethosor** [comment]
Yeah, partial support for furnaces is better than none. Doc updates would be great. Feel free to merge when it's ready and tested.

**Comment by myk002** [comment]
I'll close this PR for now, but the related issue is still there and keeps a reference to this PR when we look at it again

**Pull request closed without merging**
