### PR TITLE
stockflow: Fix "integer expected" problem in stockflow

### LINKED ISSUE #1044: Error from stockflow
After saving and reloading a fort in which stockflow had been in use, got the following error some time after unpausing:

```
C:\Users\Kelly\df_43_05_win\hack\lua\plugins\stockflow.lua:1097: Cannot write field manager_order.amount_left: integer expected.
stack traceback:
        [C]: in metamethod '__newindex'
        C:\Users\Kelly\df_43_05_win\hack\lua\plugins\stockflow.lua:1097: in function 'plugins.stockflow.create_orders'
        C:\Users\Kelly\df_43_05_win\hack\lua\plugins\stockflow.lua:91: in function 'plugins.stockflow.finish_bookkeeping'
```
Doesn't crash, but the expected jobs are not added. The message recurs each time the bookkeeper updates stock records.

Stockflow was working prior to the save/reload.

DF 0.43.05, Win64, dfhack 0.43.05-alpha3. Save available upon request.

### PR DESCRIPTION
**Pull request by ab9rf**
This appears to resolve #1044.

### CODE REVIEW

**Comment by dscorbett** [comment]
Instead of using `math.floor`, use `//` (floor division).

**Comment by lethosor** [comment]
It's worth noting that using the // operator would break the lua syntax checking script, since it uses Lua 5.2 (5.3 isn't available on Travis). That's not a good reason not to use that operator, though. I'm looking into solutions on the Travis side - in the worst case, Lua doesn't take that long to build, and the binaries could probably be cached to avoid building it every time.

**Comment by dscorbett** [comment]
Even this new version is unnecessarily complex: `(x - (x % y)) // y` can be simplified to `x // y` for any finite numbers `x` and `y`. You only need one line to calculate `amount`; see the code in my previous comment.

**Comment by lethosor** [comment]
Sorry, not sure how I missed that. I'll change it, and probably use math.floor for now until I can get Lua 5.3 working.

**Comment by dscorbett** [comment]
My recommendation of `//` was too hasty. `//` produces the right answer, but does not convert its result to an integer if either input is a float. I didn’t check whether it is safe to use this operator in this script.

**Comment by lethosor** [comment]
Sure enough. I'll leave it as-is, then.

**Comment by ab9rf** [comment]
They should be integers, but "should" is here a somewhat fuzzy concept given Lua's odd definition of "integer".

**Comment by lethosor** [comment]
Lua 5.3 has more of a distinction (e.g. `3.0` and `3` will print differently but compare as equal, while they would both print as "3" in Lua 5.2).

**Pull request merged**
