### PR TITLE
Implement #804, move some functions to Units

### PR DESCRIPTION
**Pull request by kazimuth**
Also colorize output from the zone plugin, and clean it up a tiny bit.

### CODE REVIEW

**Comment by BenLubar** [comment]
@kazimuth you've got some trailing whitespace that Travis is objecting to.

**Comment by kazimuth** [comment]
Fixed, thanks @BenLubar.

**Comment by expwnent** [comment]
#804 

I think references don't work in titles.

**Comment by lethosor** [comment]
Need to confirm if this stuff works with MSVC:
```cpp
// ZONE FILTERS (as in, filters used by 'zone')

// Maps parameter names to filters.
unordered_map<string, function<bool(df::unit*)>> zone_filters = {
    { "caged", isContainedInItem },
    { "egglayer", isEggLayer },
```

**Comment by BenLubar** [comment]
Merge conflict is just in the `#include` part of Units.cpp. As for compatibility:

```
..\..\..\plugins\zone.cpp(1320): error C2552: 'zone_filters' : non-aggregates cannot be initialized with initializer list [C:\Users\Owner\Documents\GitHub\dfhack\build\VC2010\plugins\zone.vcxproj]
..\..\..\plugins\zone.cpp(1321): error C2078: too many initializers [C:\Users\Owner\Documents\GitHub\dfhack\build\VC2010\plugins\zone.vcxproj]
..\..\..\plugins\zone.cpp(1322): fatal error C1903: unable to recover from previous error(s); stopping compilation [C:\Users\Owner\Documents\GitHub\dfhack\build\VC2010\plugins\zone.vcxproj]
```

**Pull request merged**
