### PR TITLE
Fix autochop

### PR DESCRIPTION
**Pull request by CannibalVox**
Add job-removal functionality to autochop, this should make it actually
function.

### CODE REVIEW

**Comment by lethosor** [comment]
What's this supposed to fix? Job removal?

I noticed an issue before your changes where woodcutters would stay around trees they just cut down (even ones with single-tile trunks) with the "fell tree" job for a few seconds before moving on to the next one, and designations wouldn't flash after the first tree they cut down. That still seems to be an issue. Also, a new issue that I only saw after these changes is a bunch of "Miner cancels dig: inappropriate dig square" announcements. They're to the southwest corner of the most recently felled trees (so far), so it may be the corner of a 16x16 block.

**Comment by ab9rf** [comment]
The "hanging around" problem is likely related to #1018 and #1014. What likely happens is that the tile is designated for chopping by the plugin by setting its designation bits. On unpause, DF clears the designation and queues a chop tree job posting. The next time the treechopping plugin runs, it sees the tree as not designated for chopping and designates it again. DF again queues a chop tree job posting. When the tree is finally cut down, DF removes the first job posting. The treechopping dwarf then looks for nearby treecutting jobs, finds one on the same square, and tries to start it, but gets canceled because there's no longer a tree there. This results in the "inappropriate dig square" announcement.

Thus, plugins that will set map designations need to check the job posting queue for jobs for that map square to avoid spamming the job queue. An option would be for the job to just post the job queue entry themselves, but I'm not sure we know how to do that yet.

**Comment by lethosor** [comment]
I'm pretty sure it was a different dwarf cancelling the mining job (not the woodcutter). I could be wrong about that, though.

Checking the postings list is probably a good way to go, unless we can create jobs ourselves (in which case inserting a posting is fairly easy).

**Comment by CannibalVox** [comment]
Yeah, this was primarily to deal with job removal.  Atm, if you set it into autochop mode, dwarfs will currently uncontrollably chop every tree on the map because there's no real way to kill the jobs once you have enough logs.  This makes "undesignate" and the autochop "i have enough logs" stuff properly remove existing jobs.  I can take care of those other things too though.

**Comment by lethosor** [comment]
Okay, makes sense. I just did a brief test and didn't look at the cancellation features, apparently.

**Comment by CannibalVox** [comment]
Is "inappropriate dig square" actually a new bug I introduced?  Not sure how I did that.

**Comment by CannibalVox** [comment]
Oh also kind of a side effect of the job removal fix, but we also correctly count designated trees, even once the designations are converted to jobs.  Dupe jobs shouldn't be the norm in ordinary play unless a player manually redesignates everything (which is certainly a thing that can happen).

**Comment by lethosor** [comment]
Does the "inappropriate dig square" issue occur on your end? I thought it could've been related to #1047, since it showed up around that time, but the issue is still occurring for me in alpha4 (64-bit OS X).

I'm also seeing my woodcutter remain next to a recently-felled tree with the "fell tree" job, or even return multiple times to the most recently-felled one, apparently trying to cut it down again. The lack of the usual flashing designation is also still an issue.

**Comment by lethosor** [comment]
@CannibalVox have you seen the "inappropriate dig square" issue on your end?

**Comment by lethosor** [comment]
Any luck with the announcement spam? I'd like to get this merged into r1, if possible.

**Comment by lethosor** [comment]
I've figured out how to get rid of the duplicated jobs (which was causing the issue with woodcutters trying to chop down already-felled trees, also mentioned in #1076). I'll look into this fix too, although I may have to manually apply it.

**Comment by lethosor** [comment]
I made a module based partly on this in 1e469453fcf947744c35c1280890482354cb39dc, hopefully to use for getplants too (#531, #1018, and similar issues). Thanks for the help!

**Pull request closed without merging**
