### PR TITLE
[buildingplan] step5: support all building types

### LINKED ISSUE #1640: buildingplan: support all building types
The next big feature I have planned for quickfort is support for all buildings in buildingplan.

I have a few questions, though, and I'm not on IRC reliably enough to ask them there:

1) How do we match an item against a building construction job item filter?

In order to support all buildings, I'll need to support a wider variety of building items, including generic building materials. buildingplan goes through all free game items and assigns pertinent ones to buildingplan-managed buildings. This is easy to do for the furniture types buildingplan currently supports, but how can we do it generically for any filter returned from buildings.lua? Say the filter says "fire-safe building material", what is the best way to select a matching item in the game world?

Edit: I just discovered dfhack.job.isSuitableItem(). Let me investigate that.
Edit2: that looks like it will work. Nice.

2) How do we assign just one of several items in a construction job?

This might become obvious once I start implementing, but just in case it's difficult, are there any special steps I have to take for assigning items to a suspended well construction job if not all items are available at the same time? Can I assign one item and keep the job suspended? are there any negative consequences of doing that?

I haven't fully designed the data structures and item selection algorithm yet, but my overall plan is this:

- general cleanup of buildingplan code to make the code easier to modify (no logic or API changes) -- move business logic out of header files, split buildingplan-lib.h into buildingplan-planner.h and buildingplan-rooms.h, move gui code back into buildingplan.cpp
- tighten up the API -- make all publicly unused methods private, remove direct access to mutable fields (this will be required for the persistent item filters feature request that was on the forums recently)
- Use lua to allocate buildingplan-created buildings so we get appropriate item filters
- When assigning an item to a construction job, filter both by construction job filters and buildingplan filters
- Generate gui material selection pages for each required item, use getFilters() to get how many items, display serialized filter at top of screen so players know what they’re selecting for, left, right arrow keys to switch between items

### PR DESCRIPTION
**Pull request by myk002**
Closes #1640

Allow buildingplan to handle all building types, update the docs, and add in little extra fixes to ensure all the new types work correctly.

Code can be reviewed after #1675 is merged.

There is a keybinding conflict with rollers that we should address. buildingplan takes over interpretation of 'q' and 'w' to adjust the min quality filter when planning mode is enabled for rollers, and then the roller speed can never be set. You can temporarily disable buildingplan for rollers, set the speed, enable buildingplan, and place the building, but that is a poor user experience. It might also break python quickfort blueprints that place rollers.

I don't really want to change the q/w hotkeys that people are used to, but a conflict is a conflict. Maybe just change the min quality hotkeys for rollers? Change all min quality hotkeys to 'A' and 'S'? What are your thoughts?

Edit: solved by changing keybindings for min and max quality.

There is also a confusing UX interaction with the automaterial plugin for constructions. currently, if planning mode is enabled, buildingplan takes precedence and places a single tile of the construction on {Enter}, regardless of what settings are set for automaterial (e.g. box select). I think the solution here is:
- for automaterial-managed constructions, let automat handle placement (that is, buildingplan doesn't intercept the {Enter} key if automaterial is enabled)
- if buildingplan planning mode is enabled for the construction type, automaterial will
  - not show the "Auto Mat-select", "Reselect Type", or "Open Placement" options
  - construct the buildings with filters instead of showing its material selection screen
  - route the building back through buildingplan to let it select materials according to its filter

But I think that can be tackled in a future PR (after I hear your thoughts on this)

### CODE REVIEW

**Comment by lethosor** [comment]
I played with this a bit after looking at #1675. Looks awesome!

> There is a keybinding conflict with rollers that we should address. buildingplan takes over interpretation of 'q' and 'w' to adjust the min quality filter when planning mode is enabled for rollers, and then the roller speed can never be set. You can temporarily disable buildingplan for rollers, set the speed, enable buildingplan, and place the building, but that is a poor user experience. It might also break python quickfort blueprints that place rollers.

> I don't really want to change the q/w hotkeys that people are used to, but a conflict is a conflict. Maybe just change the min quality hotkeys for rollers? Change all min quality hotkeys to 'A' and 'S'? What are your thoughts?

Yeah, I would be okay with `a` and `s`. Not sure if there are other special cases where _those_ conflict, though. I suppose one option would be to accept q/w *and* a/s for most building types, unless there is a conflict.

In any case, I think the max quality keys should also match (a/s and Q/W seem confusing to me, particularly since their positions on a QWERTY keyboard don't match their on-screen positioning). a/s and z/x could also be an option, although that opens the door to more possible conflicts. Combinations with modifiers (Shift in this case) are probably less likely to result in conflicts.

I guess I don't have a strong suggestion, but I also doubt many people have memorized these specific key combinations, and they're displayed on-screen, so I would be fine with changing them entirely if that's easiest. (I'm also not sure if you've already made code changes since writing up the PR, so apologies if I missed something.)

**Comment by myk002** [comment]
> I played with this a bit after looking at #1675. Looks awesome!

Thanks :D I'm really happy with how it came out.

> Combinations with modifiers (Shift in this case) are probably less likely to result in conflicts.
> [...]
> I would be fine with changing them entirely if that's easiest.

ok, I think I'll go with {Shift}q and {Shift}w for adjusting max quality and {Shift}a and {Shift}s for adjusting min quality, then. Just 'a' and 's' conflict with trackstop speed and roller direction, respectively.

**Review by lethosor — APPROVED** [review]

**Comment by lethosor** [comment]
As for the automaterial conflict: communicating between plugins is a bit tricky. Interposed vmethods do support priorities, though (`IMPLEMENT_VMETHOD_INTERPOSE_PRIO`), so you might be able to use that to run certain logic before/after automaterial. Not sure how much that would help.

I'll try to take a closer look tomorrow at how automaterial is dealing with this - I'm assuming it didn't support planning constructions without the necessary materials before, right?

**Comment by myk002** [comment]
> As for the automaterial conflict: communicating between plugins is a bit tricky.

I was thinking of using the Lua layer for communication -- checking to see what's enabled on both sides, automat registering the building with buildingplan, etc.

> I'll try to take a closer look tomorrow at how automaterial is dealing with this - I'm assuming it didn't support planning constructions without the necessary materials before, right?

It currently uses the UI to build, with an alternate path through Buildings::constructWithItems() for handling hollow rectangles. My preliminary plan was to always construct via the API so we have more control over it. But we'll see. I haven't studied the code very deeply yet.

**Comment by lethosor** [comment]
Yeah, communicating through Lua could definitely work. I was thinking of past inter-plugin communication attempts where one or both of the plugins haven't exposed Lua functionality.

**Pull request merged**
