### PR TITLE
Allow scripts to self-enable and automatically restore state

### PR DESCRIPTION
**Pull request by myk002**
Basic infrastructure for #2338

This simple plugin scans all scripts and performs the following actions:
- hooks global `onStateChange()` functions up to `dfhack.onStateChange`
- catalogs script `isEnabled()` functions so they can be surfaced via the `enable` command

Sample change to the prioritize script to implement `isEnabled()`:
```lua
function isEnabled()
    for k in pairs(get_watched_job_matchers()) do
        return true
    end
    return false
end
```

### CODE REVIEW

**Comment by lethosor** [comment]
Does this need a plugin? For core functionality like this, I think it would be ok to install an onStateChange hook in dfhack.lua (I thought we did already, actually). I'm not sure if there's anything else you're using the plugin for here.

**Comment by myk002** [comment]
The plugin is also acting as the liaison for the enable built-in for listing the state of enable-able scripts. The plugin is certainly light on functionally, though, and if there is a better place for the logic, we can move it

**Comment by myk002** [comment]
A potential modification to this algorithm: instead of scripts declaring global onStateChange functions that are attached by script-manager, they could modify dfhack.onScriptChange themselves in the main script body. For example, [modtools/fire-rate](https://github.com/DFHack/scripts/blob/113d0a85f734f84d4ee4f584819705b26a5ec9f3/modtools/fire-rate.lua#L414) does this.

The advantage is that modified scripts get their hooks updated automatically, which would be useful during development or if scripts can be added by steam workshop while the game is running

The disadvantage is that the names are chosen by the scripts themselves, which can lead to naming collisions if the script authors are not consistent (or if a script with a similar relative path is visible in a different script_path). For example, modtools/fire-rate chose the key "fire-rate" whereas script-manager would have keyed it by 'modtools/fire-rate'.

**Comment by myk002** [comment]
I should note that what I liked about it being a plugin was that the order of events was well defined. I've already discovered how bad an idea it is to load script code before plugins were initialized. The plugin structure guarantees that core and the plugins will be in an appropriate state.

**Comment by lethosor** [comment]
> The plugin is also acting as the liaison for the enable built-in for listing the state of enable-able scripts. The plugin is certainly light on functionally, though, and if there is a better place for the logic, we can move it

How does it do that? It only has `plugin_init()` and `plugin_onstatechange()`, and I don't see any changes to PluginManager.

I think `enable` could integrate with PluginManager (or a new ScriptManager?) directly, rather than going through a plugin.

I think one of my general concerns here is that it shouldn't be possible to break core behavior with `unload script-manager`, and that seems to me like it would break some stuff.

> A potential modification to this algorithm: instead of scripts declaring global onStateChange functions that are attached by script-manager, they could modify dfhack.onScriptChange themselves in the main script body. For example, [modtools/fire-rate](https://github.com/DFHack/scripts/blob/113d0a85f734f84d4ee4f584819705b26a5ec9f3/modtools/fire-rate.lua#L414) does this.

Likewise, I think this is something that dfhack.lua could easily handle as well. It already loads scripts to support `enable`.

> 
I should note that what I liked about it being a plugin was that the order of events was well defined. I've already discovered how bad an idea it is to load script code before plugins are initialized. The plugin structure guarantees that core and the plugins will be in an appropriate state.

Plugin load order isn't defined. Depending on the system, `script-manager` could load before other plugins, or first, or last (depending on directory order). If we define it to be alphabetical, then any plugins after `sc` would still be loaded later. On the other hand, something in core could reliably order itself before or after all plugins load.

**Comment by myk002** [comment]
> > The plugin is also acting as the liaison for the enable built-in for listing the state of enable-able scripts.
> 
> How does it do that? It only has `plugin_init()` and `plugin_onstatechange()`, and I don't see any changes to PluginManager.

`plugin_onstatechange()` calls `Lua::CallLuaModuleFunction(out, L, "plugins.script-manager", "reload");` on `SC_CORE_INITIALIZED`. That's where the plugin lua modules, scripts are scanned, and the `isEnabled()` cache is built. The `enable` command code in `Core.cpp` calls the script manager's Lua `list()` function to list enableable scripts.

> I think `enable` could integrate with PluginManager (or a new ScriptManager?) directly, rather than going through a plugin.
>
> I think one of my general concerns here is that it shouldn't be possible to break core behavior with `unload script-manager`, and that seems to me like it would break some stuff.

Yes, we could shift this into core by making script-manager.lua a library module and calling it's `reload` function from someplace in Core just before the `SC_CORE_INITIALIZED` event is sent. That should be fine.

> > A potential modification to this algorithm
> 
> Likewise, I think this is something that dfhack.lua could easily handle as well. It already loads scripts to support `enable`.

I do not think this functionality can go into dfhack.lua directly. dfhack.lua is loaded well before all plugins have finished initializing, leading to the same problem I had with `overlay` when I tried to do this same sort of scanning during `plugin_init`.

> > I should note that what I liked about it being a plugin was that the order of events was well defined.
> 
> Plugin load order isn't defined. Depending on the system, `script-manager` could load before other plugins, or first, or last (depending on directory order). If we define it to be alphabetical, then any plugins after `sc` would still be loaded later. On the other hand, something in core could reliably order itself before or after all plugins load.

Plugin load order wouldn't matter here -- no lua code is scanned during `plugin_init`. It's only during `SC_CORE_INITIALIZED` that lua is scanned.

I'll move the code out of a plugin and into core and we can see what that looks like.

**Comment by lethosor** [comment]
Ok, so the purpose of the plugin was to handle the SC_CORE_INITIALIZED event, then? If dfhack.lua runs before that event fires, it could install an onStateChange handler to handle that event (there already is one: `dfhack.onStateChange.DFHACK_PER_SAVE`).

Putting the call to Lua in the necessary spot in Core.cpp works just as well, of course.

**Comment by myk002** [comment]
> it could install an onStateChange handler
> 
> Putting the call to Lua in the necessary spot in Core.cpp works just as well, of course.

ha, that's true. Which would you prefer?

**Comment by lethosor** [comment]
Either one. Putting it in Core makes it a bit easier to guarantee execution order, I suppose.

Another question: how do you plan to deal with scripts that are added to a script folder after the initialization step runs?

**Comment by myk002** [comment]
Is there a way to detect that a script has been added without polling?

We might need to just document that if you've just hot-loaded a mod, you'll need to call script-manager.reload() (or some easy to type substitute)

We could mitigate this somewhat by not caching the isEnabled() functions; just do a full scan every time `enable` is run. This would at least pick up new enableable scripts. It's not like `enabled` is run so often that the cache would make a difference

**Comment by lethosor** [comment]
Sorry I am late. ffd646462ab4897399cde9a5da5252add24ebe18 looks like a reasonable approach to me. I'm assuming invoking a script would also attempt to locate the script before bailing, even if it hadn't previously existed?

I'm happy with this being in core.

**Comment by myk002** [comment]
> I'm assuming invoking a script would also attempt to locate the script before bailing, even if it hadn't previously existed?

That's correct. That's what it did before and the logic for searching for scripts upon invocation hasn't changed.

**Pull request merged**
