### PR TITLE
zero ccache stats between runs

### LINKED ISSUE #3514: Clarify dreamfort help
Especially around how to keep miners on the right level. See discord discussion here: https://discord.com/channels/793331351645323264/807444467140788254/1124522719409606676

### PR DESCRIPTION
**Pull request by myk002**
and allow the cache to expand past the persisted max size during the build

Fixes #3514 just because I needed an innocuous change to test the rebuild speed

### CODE REVIEW

**Comment by lethosor** [comment]
Why is `--zero-stats` desirable?

**Comment by myk002** [comment]
so we get statistics specific to the last build and not averages from the beginning of time

**Comment by lethosor** [comment]
I guess a better question is: what are those stats used for? If they are used to determine which files to evict after multiple builds, I would think we _do_ want them to persist between runs. If they are informational only, then it probably doesn't matter.

**Comment by myk002** [comment]
They are for measuring the effectiveness of the cache, for informational purposes only. clearing the stats does not affect the LRU measurements in the cache itself.

see: https://interrupt.memfault.com/blog/ccache-debugging#1-measure-total-cache-misses

**Pull request merged**
