### PR TITLE
Import Vjek's scripts from the wiki

### PR DESCRIPTION
**Pull request by PeridexisErrant**
[*Source on the wiki*](http://dwarffortresswiki.org/index.php/User:Vjek)

Vjek's scripts are pretty much classic at this point, and there's a reasonably wide user base.  However installation can be tricky - at the very least, more so than coming included - and not being on Github Lethosor's proposed inclusion system won't work.  Given that upstream changes are very slow now the scripts are mature, I suggest merging them entirely.

Currently (two commits) all I've done is import the .lua files and added appropriate documentation.  It is likely that style or substantive changes might be needed (and I've heard of fourth-party-updates), so this pull request is for discussion rather than immediate merging.  Thoughts?

### CODE REVIEW

**Comment by expwnent** [comment]
I'll just ramble off my thoughts.

My biggest hesitation is naming conventions. There are old scripts in the repo that don't follow this convention I haven't gotten around to fixing, but in general scripts should be named as simply and descriptively as possible. elevate_physical is fine, but someone who hasn't seen it before would have no idea what armoks_blessing does and if they happen to be looking for a script which does what that script does, the name armoks_blessing isn't going to be what they're looking for if they browse the scripts folder. At some point we should really try to standardize camelCase vs underscores_between_words vs dashes-between-words but that's a much bigger project because df-structures are pretty chaotic that way.

Vjek's scripts are intended for users more than modders so I suppose they should go in the main scripts folder so people don't have to type out long subfolders every time (modders can just copy+paste so it's less of an issue), but we don't want to clutter the main folder too much and make it hard to find things but then again that's sort of a pre-existing problem but then again it's something we/I should really fix at some point.

At some point we'll have to start managing scripts and subfolders in a smarter way as the number of scripts increases. There's certainly a fundamental difference between scripts intended for modders and scripts intended for players. Players shouldn't be expected to have as high of a DFHack skill level as modders so they should be easier to use. "Cheat" scripts like these (and I use the term in a non-judgmental way) are more for players but can also be useful for testing purposes.

While we're at it, I also support including Roses' script system as soon as he gives the OK and adds one or two features I already discussed with him, and I'm not sure why @lethosor hasn't merged in his custom script repo. Are there any other script libraries we should consider including?

Backwards compatibility is relevant. I strongly support standardizing scripts, especially the way they process arguments. Not all of the scripts already in the repo use the new processArgs system (but they should). The benefit of standardization is that it's easier for players and modders to learn / memorize how to use new scripts. The drawback is breaking backwards compatibility for 3rd party scripts. In general I think backwards compatibility is good, but if there's a good reason then we should do it the better way. It would be inconvenient for modders if we incorporated a 3rd party script library and changed the syntax to match the new standard but in the long run it's better for things to be standardized.

It's not as big of a problem as it seems because modders can "override" DFHack scripts by putting scripts in the raw/scripts folder, but still.

**Comment by expwnent** [comment]
Relevant thread: #667

**Comment by expwnent** [comment]
Relevant forum thread: http://www.bay12forums.com/smf/index.php?topic=152920.0

**Comment by lethosor** [comment]
PeridexisErrant actually renamed all of the scripts to use dashes instead of underscores - there's one place in the readme that still refers to elevate_physical, though.

I was holding off on #667 until there was more of a consensus on it - it's a convenient approach for me and others (Max, Roses, others?) that store scripts on GitHub, but less so for people that store them on the forums or DFFD. Of course, it would be good to encourage people to use git so they can incorporate changes made by others (especially in this repo) - dfstatus, for example, has gone through a lot of cleanup and had some features added, which I don't think the original author has picked up on.

**Comment by PeridexisErrant** [comment]
I'm happy to change the names of the scripts if you think that's important - and as a general principle I agree (and changed to dash-words for this reason.  However in this case I think maintaining a clear link back upstream justifies the somewhat odd choice.

That said, I think this is ready to merge and we can address the bigger issues as part of a longer-term response to #670.

**Pull request merged**
