### PR TITLE
Experiments with Sphinx for generating documentation

### LINKED ISSUE #597: lua plant_tree_info.body is one-dimensional rather than two
When accessing `plant_tree_info.body[index]` in lua scripts, the return value will be a single `plant_tree_tile`, rather than an array of `plant_tree_tile` containing all the information on that z-level. This renders scripts which want to get detailed information about a tree's form invalid. This is also the case with `plant_tree_info.roots`.

### LINKED ISSUE #670: Improve project structure; ensure documentation is clear and complete
~~The `startdwarf` script is completely undocumented, as is the `hide` command.~~  *Fixed by #671*

Where there's two, there's probably more - it would be good if someone checked that each script, plugin, or command is at least mentioned in the readme to not it's existence, and preferably include some basic information.

This issue has evolved into part of a larger discussion of DFHack structure.  See the thread of comments and forum links in #667 for more information.

### PR DESCRIPTION
**Pull request by PeridexisErrant**
[Sphinx](http://sphinx-doc.org) is a set of documentation tools first designed for the Python language documentation, and later generalised.  Concrete benefits of switching right now include better HTML generation, and a cleaner main directory - but it's not done yet.

In the near future, this will enable significant cleanup and restructuring of the documentation.  For example, it should be possible to arrange documentation by type (eg scripts, plugins, builtins), and then pull parts of each onto a page for a particular kind of use (eg bugfixes, adv. mode, etc).

Eventually (ie in a future pull), the autodoc functionality may pull documentation for each script or plugin from it's source code.  This helps with a number of issues from stale documentation, to ensuring completeness (via linting scripts / travis), to scripts being pulled in from third-party repositories.

This may close #670, is related to #677, and closes #597.

To build the docs, you need Python and Sphinx (`pip install sphinx`); then just run `make html` in the main DFHack directory and the docs will be generated.  You can read them by opening `./README.html` in your preferred browser.

### CODE REVIEW

**Comment by lethosor** [comment]
Does this still install the HTML documentation to `hack/`? (If there are more files generated now, it may be best to move them to a subfolder, say `hack/docs/`.)

**Comment by PeridexisErrant** [comment]
Generated docs are placed in `hack/docs/_build/html/README.html`, which I think is actually a little *too* indirect.  I agree though that having them directly in `hack` was getting cluttered... so I've set up `hack/README.html`, as a file which just instantly redirects to the actual docs.

**Comment by PeridexisErrant** [comment]
I think this is both stable and enough of an improvement over the status quo to be merged now.  I do intend to take this further, but it's at a natural break point now.

**Comment by PeridexisErrant** [comment]
Further work could (concretely) improve the structure within the user manual (old readme.rst, now readme/plugins/scripts files), cross-reference all mentions of various DFHack tools as internal links, and investigate more advanced structures or uses.

However:  right now it's stable, at a natural break point, and (IMO) a big improvement over the previous situation.  Any objections to merging in order to avoid nightmare doc rebasing, and continuing after the next big release?

**Comment by expwnent** [comment]
Does it generate correctly on all OSes? Since it's used interally it's less of an issue but still.

I like the idea of automatically generating documentation from the source, but the Sphinx website says it doesn't support Lua/ruby yet. As time goes on more of the stuff end users use are scripts instead of plugins, and the C++ side becomes more "developer" territory.

It seems like a step in the right direction. I'd like to take a little time to look it over in more detail.

**Comment by PeridexisErrant** [comment]
It should be totally OS-independent, since it runs on top of Python (and is used to document the language).  I've been working mostly under Windows, but no problems in Ubuntu either once Sphinx is installed.

Docs from source are a longer term plan.  As you note it's not natively supported for Ruby and Lua (yet), but there's a fairly easy workaround in the rst `.. include::` directive.  Just set aside a multiline string for documentation, and it can get pulled into the main docs.  That's a separate project though, IMO.

And since an online version would be an obvious goal and nice thing for users, I set up a test copy at http://peridexiserrant.neocities.org

**Comment by expwnent** [comment]
I'm looking at it now. Scattered thoughts.

I took a quick double-check around various documentation generators and I agree this looks like the best one for the project since it makes good output and it supports many languages. There is a downside that it isn't integrated into github but the docs it makes are easier to read than rst files. The other downside is that setting up DFHack fully would also require python, but I guess that's not too bad. Having the DFHack submodule-ize python instead would probably be excessive.

I would prefer it to be incorporated into the current cmake system instead of just having a naked makefile but I'm not sure why. If the makefile in the root directory builds the docs instead of the program that might confuse people. I guess it'd be nice to be able to just say "make" in the build directory and have it update the docs too. I'd definitely like it to only regenerate the docs if a relevant file changed, which CMake would help with.

Docs from source should work for the C++ side, right? Sphinx does support C++.

Unless Sphinx requires otherwise I'd prefer long lines over manual text-wrapping. It lets the text processor decide when to do linebreaks. See changes to NEWS, and a few other places.

This would also provide a way that we can document general know-how about df-structures and how the game uses them, such as [this](https://gist.github.com/warmist/3017dc796a6173c215bb).

Eventually I'd definitely like to have some sort of online form of the docs, because new users / people who are considering becoming new users won't otherwise be able to see the docs.

If at all possible I'd like conf.py to read the DFHack version from CMakeLists, or both to read it from the same file. That string should be set exactly once for the entire project so that there's no chance of anyone forgetting to update it in multiple places. Also technically right now it should say r3 since CMakeLists hasn't been bumped yet. While I'm at it, I think from now on after a release we should immediately increment the release number to the next release for the develop branch so that we avoid confusion. So it's wrong under current policy but right under the next policy but really it should be reading it from CMakeLists or both should be reading it from the same place.

It should certainly exclude the depends/ folder. That contains dependencies that aren't our source code so they aren't our problem to document. I think it ignores them anyway effectively, but I'm persnickety like that.

If a file is deleted or renamed will its generated documentation html be deleted automatically?

~~Please incorporate the changes [here](https://github.com/DFHack/dfhack/commit/5bf3093139cf63b273b06dce014b6cb60001fb4f#diff-0b4c88d5d2efe959f0ce3f8762344c4dL180) into the new files so they don't get lost.~~ Never mind, it looks like you did.

Scripts.rst: shouldn't documentation of subfolders be in a separate file for better organization? Ideally each script should have its own. (And very ideally it should be autogenerated from the comments).

My mistake: in script.rst, argName4 should be the list of strings {"]", "asdf", "foo"}.

It should mesh well with the third party scripts system. Third party scripts are in submodules in scripts/3rdparty/whoever, and they each contain a CMake file to indicate where to install them. These scripts also require documentation, and it should be easy to find their documentation, ideally without even knowing that they were 3rd party scripts, since you won't always know from looking at a script that it is. I'm not sure what the right answer is, since they might be installed into different subfolders, especially for Roses' scripts.

**Comment by PeridexisErrant** [comment]
Scattered responses:

* Github integration / online reading would be good.  It looks like the best options are GitHub Pages (somewhat clumsy), or [Read the Docs](https://read-the-docs.readthedocs.org/en/latest/features.html) (external but literally designed for this).  The .rst files actually stay online in the repo, just under the `docs` directory, so people can still read them in the repo.

* Python required:  yes, this is a new dependency - if you weren't running the travis scripts and now want to build docs.  Not much to say here.

* Make system:  definitely want this integrated.  However I am more likely to break the system than upgrade it.  Same goes for single source of version number, etc.  This can all be extracted by code in `conf.py`, so long as the string ends up in the current variable name in module scope.  Would you mind taking on the makefile integration?

* Only rebuild changed documentation:  this is the default behaviour.  You can also `make clean` by deleting the build dir (`docs/_build`) of course.  If a source .rst file is deleted the builder will show warnings (due to eg. still being in a table of contents); I'm not sure if the html is deleted without `clean`.

* Manual line wrapping:  Sphinx joins lines, so it generally makes sense to manually wrap for readability as raw text - the html will be the same either way.  `NEWS` is special in that the auto-wrap would but the entirety of each release into one paragraph, so I wrapped it in a literal block (which then needs manual wrapping in output too, or gets cut off).  Happy to revert my manual wrapping, or properly format as rst - I just thought the latter might be a bit too much without approval.

* Docs from source - obviously a nice idea, probably two projects to do.  (1), the C++ side.  Natively supported, requires someone reasonably fluent in C++ (not me).  (2), the scripts.  Not natively supported, but we can fake it by pulling text between matching lines from arbitrary text files - such as eg. a multiline comment in `$myscript.lua`.  See below.

* `Scripts.rst`:  the current version is a minimal-change version to get us onto a new system.  Yes, it can be improved a lot.  My plan is basically to wait until this is merged, work out how internal links should happen (because I don't want to have to fix that if it's not right the first time), move the entry for each script into the corresponding file, and then work out whether to pull them directly into a single file or one per subdir.

* 3rdparty scripts:  Once we've got autogen working, it's just a matter of automatically building the index file.  Should be fairly simple, or at least no more difficult than now...

**Comment by expwnent** [comment]
* readthedocs looks good. I'll look into it.

* From [here:](http://sphinx-doc.org/invocation.html#cmdoption-sphinx-build-D) if we use "sphinx-build -D version=blah release=blah" from CMake that should solve a few of the problems.

* Leave NEWS as you left it for now to help with merging. Eventually it should be proper rst format.

**Comment by PeridexisErrant** [comment]
I just added and pushed a function to get the string out of the CMakeLists file, but that works too.  If the full build uses the `-D` flag, we could have conf.py set it to something like `non-release documentation` for clarity.

Sounds good.

**Comment by PeridexisErrant** [comment]
Here's a demo of hacky autodoc support for scripts:  https://github.com/PeridexisErrant/dfhack/commit/8306fc07e776848ca602306f796c9e65bfd24dab

There's probably a better way to do it, so I'm leaving that aside for no in favor of getting internal links to work.

**Comment by expwnent** [comment]
Ever get an error like this?

C:\Games\DF\dfhack\build\VC2010>msbuild /m /p:Platform=Win32 /p:Configuration=Release dfhack_docs.vcxproj
Microsoft (R) Build Engine version 4.6.79.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 9/24/2015 1:05:01 AM.
     1>Project "C:\Games\DF\dfhack\build\VC2010\dfhack_docs.vcxproj" on node 1
       (default targets).
     1>Project "C:\Games\DF\dfhack\build\VC2010\dfhack_docs.vcxproj" (1) is bui
       lding "C:\Games\DF\dfhack\build\VC2010\ZERO_CHECK.vcxproj" (2) on node 1
        (default targets).
     2>InitializeBuildStatus:
         Creating "Win32\Release\ZERO_CHECK\ZERO_CHECK.unsuccessfulbuild" becau
         se "AlwaysCreate" was specified.
       CustomBuild:
         Checking Build System
         CMake is re-running because C:/Games/DF/dfhack/build/VC2010/CMakeFiles
         /generate.stamp is out-of-date.
           the file 'C:/Games/DF/dfhack/CMakeLists.txt'
           is newer than 'C:/Games/DF/dfhack/build/VC2010/CMakeFiles/generate.s
         tamp.depend'
           result='-1'
         -- Configuring done
         CMake Warning (dev) in library/CMakeLists.txt:
           Policy CMP0022 is not set: INTERFACE_LINK_LIBRARIES defines the link
           interface.  Run "cmake --help-policy CMP0022" for policy details.  U
         se the
           cmake_policy command to set the policy and suppress this warning.

           Target "dfhack" has an INTERFACE_LINK_LIBRARIES property which diffe
         rs from
           its LINK_INTERFACE_LIBRARIES properties.

           INTERFACE_LINK_LIBRARIES:

             protobuf-lite;clsocket;lua;jsoncpp;dfhack-version;psapi;dfhack-md5
         ;dfhack-tinyxml;dfhack-tinythread

           LINK_INTERFACE_LIBRARIES:



         This warning is for project developers.  Use -Wno-dev to suppress it.

         -- Generating done
         -- Build files have been written to: C:/Games/DF/dfhack/build/VC2010
       FinalizeBuildStatus:
         Deleting file "Win32\Release\ZERO_CHECK\ZERO_CHECK.unsuccessfulbuild".
         Touching "Win32\Release\ZERO_CHECK\ZERO_CHECK.lastbuildstate".
     2>Done Building Project "C:\Games\DF\dfhack\build\VC2010\ZERO_CHECK.vcxpro
       j" (default targets).
     1>InitializeBuildStatus:
         Touching "Win32\Release\dfhack_docs\dfhack_docs.unsuccessfulbuild".
       CustomBuild:
         Building Custom Rule C:/Games/DF/dfhack/CMakeLists.txt
         CMake does not need to re-run because C:\Games\DF\dfhack\build\VC2010\
         CMakeFiles\generate.stamp is up-to-date.
         Building HTML documentation with Sphinx
         Traceback (most recent call last):
           File "c:\programs\python 3.5\lib\runpy.py", line 170, in _run_module
         _as_main
             "__main__", mod_spec)
           File "c:\programs\python 3.5\lib\runpy.py", line 85, in _run_code
             exec(code, run_globals)
           File "C:\Programs\Python 3.5\Scripts\sphinx-build.exe\__main__.py",
         line 9, in <module>
           File "c:\programs\python 3.5\lib\site-packages\sphinx\__init__.py",
         line 51, in main
             sys.exit(build_main(argv))
           File "c:\programs\python 3.5\lib\site-packages\sphinx\__init__.py",
         line 61, in build_main
             from sphinx import cmdline
           File "c:\programs\python 3.5\lib\site-packages\sphinx\cmdline.py", l
         ine 23, in <module>
             from sphinx.application import Sphinx
           File "c:\programs\python 3.5\lib\site-packages\sphinx\application.py
         ", line 37, in <module>
             from sphinx.builders import BUILTIN_BUILDERS
           File "c:\programs\python 3.5\lib\site-packages\sphinx\builders\__ini
         t__.py", line 23, in <module>
             from sphinx.util import i18n, path_stabilize
           File "c:\programs\python 3.5\lib\site-packages\sphinx\util\i18n.py",
          line 15, in <module>
             from babel.messages.pofile import read_po
           File "c:\programs\python 3.5\lib\site-packages\babel\messages\__init
         __.py", line 12, in <module>
             from babel.messages.catalog import *
           File "c:\programs\python 3.5\lib\site-packages\babel\messages\catalo
         g.py", line 23, in <module>
             from babel.dates import format_datetime
           File "c:\programs\python 3.5\lib\site-packages\babel\dates.py", line
          28, in <module>
             from babel.util import UTC, LOCALTZ
           File "c:\programs\python 3.5\lib\site-packages\babel\util.py", line
         278, in <module>
             from babel import localtime
           File "c:\programs\python 3.5\lib\site-packages\babel\localtime\__ini
         t__.py", line 21, in <module>
             from babel.localtime._win32 import _get_localzone
           File "c:\programs\python 3.5\lib\site-packages\babel\localtime\_win3
         2.py", line 18, in <module>
             tz_names = get_global('windows_zone_mapping')
           File "c:\programs\python 3.5\lib\site-packages\babel\core.py", line
         58, in get_global
             _global_data = pickle.load(fileobj)
         TypeError: an integer is required (got type str)
     1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.ta
       rgets(151,5): error MSB6006: "cmd.exe" exited with code 1. [C:\Games\DF\
       dfhack\build\VC2010\dfhack_docs.vcxproj]
     1>Done Building Project "C:\Games\DF\dfhack\build\VC2010\dfhack_docs.vcxpr
       oj" (default targets) -- FAILED.

Build FAILED.

       "C:\Games\DF\dfhack\build\VC2010\dfhack_docs.vcxproj" (default target) (
       1) ->
       (CustomBuild target) ->
         C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.
       targets(151,5): error MSB6006: "cmd.exe" exited with code 1. [C:\Games\D
       F\dfhack\build\VC2010\dfhack_docs.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:05.17

C:\Games\DF\dfhack\build\VC2010>

**Comment by expwnent** [comment]
It's the same error even if I type the sphinx-build thing manually.

**Comment by PeridexisErrant** [comment]
...no, I've never seen that before.  Maybe it's a Python 3.5 issue, since that's only a week old or so?  I've been building docs without any problems from Py3.4.3 and Sphinx 1.3.1

**Comment by expwnent** [comment]
It was [this issue.](https://github.com/sphinx-doc/sphinx/issues/1976)

The fix there worked.

**Comment by expwnent** [comment]
If you want to work some more you may want to pull [this](https://github.com/expwnent/dfhack/tree/cmake-sphinx).

**Pull request merged**
