### PR TITLE
UI fixes for gui/design

### LINKED ISSUE #4195: visual glitch in gui/design in ascii mode
gui/design will show unrelated characters from other parts of the screen instead of the regular "X" when designating tiles for digging. Graphics version looks fine.

https://github.com/DFHack/dfhack/assets/136035179/7d01d24d-fe15-473f-8579-648837da922f

### PR DESCRIPTION
**Pull request by MagistrumT-T**
We were neglecting to set the ch, fg, bg, etc... to the cur_pen, so it worked fine in graphics but not in ascii. Plainly painting the pen made by get_pen() solves the issue.

Fixes: #4195

### CODE REVIEW

**Review by myk002 — COMMENTED** [review]
Could you add a line to the fixes section in the changelog?

**Comment by MagistrumT-T** [comment]
Added the change to the gui/design so that it now fixes #4202

**Comment by myk002** [comment]
The change to `gui/design` should be done in a separate PR against the scripts repo

**Review by myk002 — APPROVED** [review]
I fixed up the history of this PR. it still includes a scripts ref update, but it's to the current upstream master, so it's ok

**Pull request merged**
