### PR TITLE
add small letters and on-off textures in top-left corners of 32x32 tiles

### PR DESCRIPTION
**Pull request by TymurGubayev**
These will be used in the `gui/biomes` script (https://github.com/DFHack/scripts/pull/637)

### CODE REVIEW

**Review by myk002 — COMMENTED** [review]
I suggest names with no spaces in them to match with existing filenames. it also looks like we prefer dashes to underscores

**Comment by TymurGubayev** [comment]
is `on-off-top-left.png` ok? It looks like 4 things now... Maybe something like `on-off--top-left.png`?

**Comment by myk002** [comment]
> is `on-off-top-left.png` ok? It looks like 4 things now... Maybe something like `on-off--top-left.png`?

a combination of dashes and underscores might be appropriate here -- `on-off_top-left.png` -- or maybe distinguish it by its tile size: `on-off_map.png`

**Comment by TymurGubayev** [comment]
renamed with underscores (on the off chance we want bottom-right etc versions later)

**Review by myk002 — APPROVED** [review]

**Pull request merged**
