### PR TITLE
reenable 3dveins

### PR DESCRIPTION
**Pull request by ab9rf**
3dveins mostly works for 50x. it has trouble with the new HFS gem-studded columns and will occasionally delete some of the gems in them, but typically not all that many of them, and it's my opinion that the impact of this is at most minimal.

in order for this to work, however, i had to make the inability to place an inclusion not a fatal error, and so that's the one change

### CODE REVIEW

**Review by myk002 — COMMENTED** [review]
could use a "new plugin" changelog entry. at this point I think it counts as "new" again.

Also, if you implement a "quiet" parameter, we could add this tool to the Fortress Autostart list in `gui/control-panel` so it can run automatically for new forts.

**Comment by ab9rf** [comment]
those are meritorious additions, hold on this until i update the PR, probably won't be before tomorrow

**Comment by ab9rf** [comment]
returning to this now that we're past sdl2

still need to rewrite for logging, so do not merge yet

**Comment by ab9rf** [comment]
switched (i think) all of the messaging to use debugfilter. still needs a changelog

**Comment by myk002** [comment]
> Also, if you implement a "quiet" parameter, we could add this tool to the Fortress Autostart list in gui/control-panel so it can run automatically for new forts.

don't forget `gui/control-panel` integration on the Autostart tab.

**Comment by ab9rf** [comment]
> Also, if you implement a "quiet" parameter, we could add this tool to the Fortress Autostart list in `gui/control-panel` so it can run automatically for new forts.

i'm not entirely sure this is a good idea, 3dveins currently causes a hang of up to a minute and having this happen automatically and silently could lead to user confusion. i'm open to ideas on how to fix that, but i don't want to delay getting this into prod where people can actually use it while we sort that out. don't let the perfect be the enemy of the good

**Review by myk002 — APPROVED** [review]

**Pull request merged**
